# Copy en espanol de cada producto. Datos numericos vienen de dados_parte1/2 (catalogo HONSN).
MARCA = 'HONSN'
PRODUTOS = [
 dict(nome='Línea Completa de Trituración', dados=None, img='wotetrack-linha-p001-01.png', chip='Áridos · Planta completa',
   note='Planta de áridos llave en mano: alimentación, trituración primaria y secundaria, cribado y transporte dimensionados como un solo circuito. De 50 a 1.500 t/h.',
   tags=['trituracion','britagem','chancadora','planta de aridos','cantera','piedra','grava','arena','linea completa','mandibulas','cono','impacto','criba','cinta'],
   lead='Planta de áridos llave en mano: alimentación, trituración primaria y secundaria, clasificación y transporte, dimensionadas como un solo circuito. GNH entrega la línea completa fija, modular o móvil, o los equipos por separado para ampliar una planta existente.',
   kpis=[('50–1.500 t/h','Capacidad de línea'),('5','Etapas'),('3','Formatos: fija · modular · móvil')]),
 dict(nome='Alimentador Vibratorio ZSW', dados='alimentador-zsw', img='alimentador-zsw-p086-01.png', chip='Áridos · Alimentación',
   note='Alimentador vibratorio con parrilla para dosificar la primaria a caudal constante y separar el fino antes de la boca. Series GZD y ZSW, de 80 a 1.500 t/h.',
   tags=['alimentador','vibratorio','parrilla','feeder','tolva','dosificacion','trituracion','cantera'],
   lead='Alimenta de forma continua y uniforme a la trituradora primaria y hace un precribado del material: la parrilla separa la tierra y el fino que no necesitan pasar por la mandíbula. Series GZD (bandeja) y ZSW (parrilla), de 80 a 1.500 t/h.',
   ventajas=['Caudal constante hacia la primaria: la línea deja de trabajar a golpes.','Precribado en la parrilla: menos desgaste de mandíbula y más producción útil.','Inclinación de montaje regulable según el material.'],
   kpis=[('80–1.500 t/h','Capacidad'),('hasta 1.200 mm','Alimentación máx.'),('2,2–55 kW','Potencia')]),
 dict(nome='Trituradora de Mandíbulas PE', dados='mandibulas-pe', img='mandibulas-pe-p019-01.png', chip='Áridos · Trituración primaria',
   note='Trituradora de mandíbulas PE / PEX: la primaria clásica, robusta y simple de mantener. Bocas de 150×250 a 1.500×1.800 mm, de 1 a 1.200 t/h.',
   tags=['mandibulas','mandibula','jaw','primaria','trituradora','chancadora','britador','cantera','roca','PE','PEX'],
   lead='La trituradora de mandíbulas de referencia: estructura simple, sólida y de mantenimiento fácil, con costo de compra e instalación contenido. Tritura roca y minerales con resistencia a la compresión de 147 a 245 MPa en fracciones gruesas, medias y finas. La serie PE es la primaria; la PEX, con boca alargada, es la de trituración fina.',
   ventajas=['Bastidor tipo E, capaz de soportar mayor fuerza de impacto.','Volante de gran diámetro: robusto y durable.','Ajuste de la abertura de salida por lainas, firme y confiable.'],
   kpis=[('1–1.200 t/h','Capacidad'),('147–245 MPa','Resistencia del material'),('5,5–380 kW','Potencia')]),
 dict(nome='Trituradora de Mandíbulas HJ', dados='mandibulas-hj', img='mandibulas-hj-p016-01.png', chip='Áridos · Trituración primaria',
   note='Mandíbula de alto rendimiento tipo europeo para trabajo pesado: cámara en V profunda y ajuste por cuña. De 55 a 1.160 t/h.',
   tags=['mandibulas','jaw','primaria','europea','trituradora','chancadora','britador','HJ','cantera','roca dura'],
   lead='Producto integral de alto rendimiento que combina lo mejor de las mandíbulas europeas y fue desarrollado para condiciones de trabajo pesado. Baja el costo por tonelada triturada y llena el hueco entre la mandíbula convencional y los equipos de gama alta.',
   ventajas=['Bastidor soldado tipo caja, con excelente durabilidad al impacto.','Cámara de trituración simétrica en V profunda: maximiza producción y relación de reducción.','Ajuste de salida por cuña, rápido y simple.','El motor vibra solidario con la máquina: ahorra espacio.','Boca de entrada más cuadrada: mejor relación costo-beneficio con bloques grandes.'],
   kpis=[('55–1.160 t/h','Capacidad'),('hasta 1.040 mm','Alimentación máx.'),('75–200 kW','Potencia')]),
 dict(nome='Trituradora de Cono SC', dados='cono-sc', img='cono-sc-p022-01.png', chip='Áridos · Trituración secundaria y terciaria',
   note='Cono hidráulico monocilíndrico con control inteligente y remoto. Cámaras C (secundaria) y F (terciaria), de 27 a 2.181 t/h, 90 a 750 kW.',
   tags=['cono','conica','cone','secundaria','terciaria','hidraulica','trituradora','chancadora','britador','SC','basalto','granito'],
   lead='Desarrollada sobre la tecnología más avanzada del mercado, integra mecánica, hidráulica, eléctrica y control inteligente con mando remoto. Frente a otros conos: mayor capacidad y menor consumo. Cámaras tipo C para trituración media (secundaria) y tipo F para fina (terciaria), con la excentricidad ajustable sin cambiar piezas.',
   ventajas=['Cámara de trituración constante: granulometría y capacidad estables durante toda la vida del revestimiento.','Sistema antipolvo por presión positiva: protege el interior y el aceite.','Revestimientos sin material de relleno: cambio más rápido y más horas de máquina en marcha.','Sistema de control inteligente con interfaz simple, que maximiza la productividad.'],
   kpis=[('27–2.181 t/h','Capacidad'),('90–750 kW','Potencia'),('C1–C2 · F1–F5','Cámaras')]),
 dict(nome='Trituradora de Impacto PF', dados='impacto-pf', img='impacto-pf-p030-01.png', chip='Áridos · Trituración secundaria',
   note='Impactor de eje horizontal para material de dureza media y baja abrasión: caliza, reciclado, asfalto. Rotores de Ø1.000 a Ø1.800 mm, de 30 a 800 t/h.',
   tags=['impacto','impactor','reversible','martillos','secundaria','caliza','reciclado','RCD','trituradora','chancadora','britador','PF'],
   lead='Diseño estructural único y fabricación avanzada. Se usa ampliamente en vialidad, ferrocarril, energía y materiales de construcción para triturar materiales de dureza media o inferior y baja abrasión, con buena forma de grano.',
   ventajas=['Boca grande y cámara alta: admite material duro y de gran tamaño, con poco polvo de piedra en el producto.','Estructura compacta, rígida, con rotor de gran inercia.','La separación entre placas de impacto y martillos se regula con facilidad, controlando la granulometría y la cubicidad.','Martillos de alto cromo: resistentes al impacto y al desgaste.'],
   kpis=[('30–800 t/h','Capacidad'),('hasta 800 mm','Alimentación máx.'),('45–710 kW','Potencia')]),
 dict(nome='Trituradora de Impacto CI', dados='impacto-ci', img='impacto-ci-p029-01.png', chip='Áridos · Trituración primaria y secundaria',
   note='Nueva generación de impactores con materiales de alta resistencia al desgaste y regulación hidráulica. Versiones primaria y secundaria/terciaria, de 60 a 2.000 t/h.',
   tags=['impacto','impactor','primaria','secundaria','hidraulico','reciclado','concreto','asfalto','escoria','trituradora','chancadora','britador','CI'],
   lead='La serie CI incorpora nuevos materiales de alta resistencia al desgaste que elevan de forma notable el rendimiento y la capacidad. Resultados probados en cantera de dureza media y baja abrasión, grava, cemento, reciclado de hormigón y asfalto y escorias.',
   ventajas=['Rotor pesado y robusto: trituración eficaz.','Martillos resistentes al impacto y al desgaste, con granulometría de salida estable.','Nuevos materiales antidesgaste: ciclos de cambio más largos y menos stock de repuestos.','Dispositivo hidráulico multifunción: regulación precisa y rápida, menos esfuerzo y menos paradas.'],
   kpis=[('60–2.000 t/h','Capacidad'),('hasta 800 mm','Alimentación máx.'),('160–1.000 kW','Potencia')]),
 dict(nome='Trituradora de Eje Vertical VSI7A', dados='vsi7a', img='vsi7a-p031-01.png', chip='Áridos · Fabricación de arena',
   note='Arenera y moldeadora de eje vertical (VSI) para arena de trituración y cubicado de agregados. De 260 a 1.115 t/h según modo.',
   tags=['VSI','eje vertical','arena','arenera','manufacturada','cubicado','moldeo','terciaria','trituradora','britador','areia'],
   lead='Nueva generación de arenera y moldeadora por impacto de eje vertical, que combina tecnología internacional con desarrollos propios. En líneas de arena manufacturada y agregados de precisión, de gran y muy gran escala, muestra un rendimiento sobresaliente.',
   ventajas=['Alimentación flexible: modos "cascada + central" y "totalmente central".','Descarga amplia: evita atascos y mejora el rendimiento.','Cámara reforzada: menor costo de desgaste y más vida útil.','Rotor de cuatro puertos: más caudal y más producto terminado.','Apertura hidráulica de la tapa y dispositivo de izaje: mantenimiento más simple.'],
   kpis=[('260–1.115 t/h','Caudal'),('2×200 a 2×500 kW','Potencia'),('<40 / <60 mm','Alimentación duro / blando')]),
 dict(nome='Criba Vibratoria HX', dados='criba-hx', img='criba-hx-p091-03.png', chip='Áridos · Clasificación',
   note='Criba circular de lubricación por aceite para trabajo pesado: 2 a 4 pisos, de 45 a 1.500 t/h. Serie HX-D de doble eje con boca ampliada.',
   tags=['criba','zaranda','peneira','vibratoria','clasificacion','cribado','pisos','malla','HX','fracciones'],
   lead='Criba de vibración circular nueva, pensada para condiciones de trabajo pesado: tecnología madura, repuestos universales, alta intensidad de vibración, estructura robusta, mantenimiento simple y larga vida. Sirve para cribado pesado, medio y fino: es el equipo ideal después de la primaria y la secundaria, y también para cribado de control y de producto final.',
   ventajas=['Inclinación de la superficie de cribado seleccionable entre 15° y 23°, para adaptarse a cada obra.','Excitador de eje excéntrico más contrapesos: transmisión estable y fuerza de excitación suficiente.','Lubricación por aceite con cambio cada seis meses: mantenimiento diario mínimo.','Capas antidesgaste en las zonas críticas.','Transmisión por poleas: la velocidad se ajusta en obra.','Rodamientos específicos para equipos vibratorios.'],
   kpis=[('45–1.500 t/h','Capacidad'),('2–4','Pisos'),('3,5 G / 4,5 G','HX / HX-D')]),
 dict(nome='Cintas Transportadoras', dados=('cinta-movil','cinta-td'), img='cinta-p005-01.png', chip='Áridos · Transporte',
   note='Cintas transportadoras móviles y fijas serie TD, anchos B400 a B2400, de 30 a 3.000 t/h. Unen los equipos y forman las pilas de producto.',
   tags=['cinta','correia','transportadora','banda','conveyor','apilador','pila','transporte','TD'],
   lead='Unen los equipos de la línea y forman las pilas de producto terminado. Versión móvil para reubicar en obra y serie TD fija para instalación definitiva, con anchos de banda de 400 a 2.400 mm y motorización según la longitud del tramo.',
   ventajas=['Ancho, velocidad y potencia se eligen por caudal, distancia y desnivel.','Versión móvil sobre orugas (CT) o ruedas para cambiar de posición sin desmontar.','Serie TD para tramos largos: hasta 50 m con motorización escalonada.'],
   kpis=[('30–3.000 t/h','Capacidad'),('B400–B2400','Ancho de banda'),('hasta 50 m','Tramo TD')]),
 dict(nome='Planta Móvil sobre Orugas WOTETRACK', dados='planta-orugas-wotetrack', img='wotetrack-p003-01.png', chip='Áridos · Planta móvil',
   note='Estación móvil sobre orugas de concepción nórdica: mandíbula, impacto, cono, arenera o criba, autopropulsada. De 60 a 500 t/h; accionamiento hidráulico, híbrido o eléctrico.',
   tags=['movil','orugas','crawler','planta','estacion','autopropulsada','mandibulas','cono','impacto','criba','cantera','reciclado','wotetrack'],
   lead='Nace de la fusión del concepto de los equipos sobre orugas del norte de Europa —su cuna— con los equipos principales HONSN, y se desarrolló como un sistema móvil de trituración y cribado de alto rendimiento. Se traslada sola por la obra o la cantera y se combina en tren: mandíbula → cono/impacto → criba.',
   ventajas=['Alta productividad: equipos principales de tipo europeo, con cámara optimizada y piezas de desgaste de calidad.','Alta fiabilidad: más de cuarenta años en equipos de minería y componentes originales.','Ahorro y ambiente: motores de marca conocida con las últimas normas de emisión, con reducción de polvo y ruido.','Seguridad: protecciones, enclavamientos, arranque y parada con un botón y paradas de emergencia al alcance.','Operación y mantenimiento simples, con plataforma de control accesible.','Tres accionamientos: totalmente hidráulico, híbrido tipo D (grupo diésel + red) y tipo E (red externa en producción).'],
   kpis=[('60–500 t/h','Capacidad'),('19','Modelos'),('3','Accionamientos')]),
 dict(nome='Planta Móvil sobre Neumáticos MTF', dados='planta-neumaticos-mtf', img='mtf-p007-03.png', chip='Áridos · Planta móvil',
   note='Línea móvil sobre neumáticos (series MTF / MTN) para roca dura, roca blanda y residuos de construcción, de 50 a 550 t/h. Cintas a bordo y patas de apoyo: sin obra civil.',
   tags=['movil','neumaticos','ruedas','semirremolque','planta','estacion','mandibulas','cono','impacto','criba','cantera','RCD','MTF','MTN'],
   lead='La línea móvil sobre neumáticos cubre de forma integral la demanda de 100 a 300 t/h en roca dura, roca blanda y residuos de construcción, con modelos que llegan a 550 t/h. Cada unidad lleva sus cintas a bordo y un sistema de patas con placas: llega a la obra y produce sin fundaciones.',
   ventajas=['Diseño modular y universal: cambiando el equipo principal se cambia el producto sin cambiar la planta.','Cintas a bordo: sin fabricar ni montar cintas externas en obra.','Sistema eléctrico a bordo, cableado de fábrica: se pone en marcha sin desmontar nada.','Plataforma de mantenimiento humanizada, con escaleras inclinadas y pasillos anchos.','Sin fundaciones: patas con placas que se recogen para el traslado.','Tolva de gran capacidad para una alimentación uniforme y estable.'],
   kpis=[('50–550 t/h','Capacidad'),('35','Modelos'),('0','Obra civil')]),
 dict(nome='Estación Modular KJ', dados='estacion-modular-kj', img='kj-p011-01.png', chip='Áridos · Planta modular',
   note='Estación de trituración modular sobre bastidores de acero: se monta sin hormigón y se reubica. Mandíbula, impacto, cono, arenera o criba, de 25 a 500 t/h.',
   tags=['modular','estacion','bastidor','sin fundacion','planta','mandibulas','cono','impacto','criba','arenera','KJ','cantera'],
   lead='Cada etapa viene montada sobre un bastidor de acero, con su alimentador, cintas y plataformas: se instala sin fundaciones de hormigón, se combina por módulos y se puede desmontar y reubicar. Es la opción entre la planta fija y la móvil cuando la obra dura años pero no para siempre.',
   ventajas=['Montaje rápido y sin obra civil: bastidores atornillados sobre suelo nivelado.','Módulos combinables: primaria, media/fina, cribado y cribado con retorno en circuito cerrado.','Se desmonta y reubica al cambiar de cantera.'],
   kpis=[('25–500 t/h','Capacidad'),('23','Modelos'),('0','Hormigón')]),
]
