# Implementos del catálogo (pág. 41-44). Clave = nombre tal cual en el catálogo (inglés).
# Valor = (nombre en español, grupo). Los de nieve y hielo no se publican (no aplican en Paraguay).
GRUPOS = ['Carga y manipulación', 'Excavación, zanjas y perforación', 'Demolición, corte y pisos',
          'Nivelación, compactación y suelo', 'Hormigón y mezcla', 'Limpieza y mantenimiento vial',
          'Forestal, paisajismo y agro', 'Tracción y acoples']
OMITIDOS = ['Snow Blower', 'High throwing snow tube', 'Snow Blade', 'Snow Bucket', 'Snow V-Blade', 'Drum ice machine']
IMPL = {
 'Standard Bucket': ('Balde estándar', 0), '4 in 1 Bucket': ('Balde 4 en 1', 0), 'Closed Bucket': ('Balde cerrado', 0),
 'High Dump Bucket': ('Balde de descarga alta', 0), 'Side dump bucket': ('Balde de descarga lateral', 0), 'Curved bucket': ('Balde curvo', 0),
 'Rock Bucket': ('Balde de rejilla para piedras', 0), 'Grapple Bucket': ('Balde con garra', 0), 'Rock Bucket Grapple': ('Balde para piedras con garra', 0),
 'Pallet Fork': ('Horquilla portapallets', 0), 'Side Shift Pallet Fork': ('Horquilla portapallets con desplazamiento lateral', 0),
 'Utility Fork': ('Horquilla utilitaria', 0), 'Fork Clamp': ('Pinza con horquilla', 0), 'Flat clamp': ('Pinza plana', 0),
 'Multi section crane': ('Grúa articulada', 0), 'Sling': ('Pluma con gancho de izaje', 0), 'Hydraulic winch': ('Cabrestante hidráulico', 0),
 'Auger': ('Hoyadora', 1), 'Bit': ('Mechas para hoyadora', 1), 'Trencher': ('Zanjadora', 1), 'Double Trencher': ('Zanjadora doble', 1),
 'Backhoe': ('Retroexcavadora trasera', 1), 'Backhoe Arm': ('Brazo retroexcavador', 1), 'Swing Backhoe Arm': ('Brazo retroexcavador giratorio', 1),
 'Digger': ('Cavadora', 1), 'Ripper': ('Escarificador', 1), 'Pile Driver': ('Hincadora de postes', 1), 'Multi-Function': ('Brazo multifunción', 1),
 'Breaker': ('Martillo hidráulico', 2), 'Hydraulic shear': ('Cizalla hidráulica', 2), 'Floor hammer': ('Martillo de piso', 2),
 'Planer': ('Fresadora de pavimento', 2), 'Road Cutting Saw': ('Sierra para cortar pavimento', 2), 'Wheel Saw': ('Sierra de disco para zanjas', 2),
 'Manhole Cover Milling Machine': ('Fresadora para tapas de registro', 2), 'Floor Grinder': ('Pulidora de pisos', 2),
 'Dozer Blade': ('Hoja topadora', 3), 'Dozer Blade (2)': ('Hoja topadora (otra versión)', 3), 'Grader': ('Niveladora', 3),
 'Land Plane': ('Nivelador de terreno', 3), 'Landscape Rake': ('Rastrillo nivelador', 3), 'Scraper': ('Raspador', 3),
 'Plate Compactor': ('Placa compactadora', 3), 'Vibratory Roller': ('Rodillo vibratorio', 3), 'Ditch Compactor': ('Compactador de zanjas', 3),
 'Lawn paver': ('Rodillo para césped', 3), 'Soil Conditioner': ('Acondicionador de suelo', 3), 'Stone screening machine': ('Criba rotativa de piedras', 3),
 'Bucket Mixer': ('Balde mezclador de hormigón', 4), 'Mixer': ('Mezcladora', 4), 'Stabilized soil mixer': ('Mezcladora de suelo estabilizado', 4),
 'Sweeper/Gutter Brush': ('Barredora con cepillo de cordón', 5), 'Advancing Sweeper': ('Barredora frontal', 5), 'Water Kit': ('Kit de agua para barredora', 5),
 'Angle Broom': ('Escoba angular', 5), 'Electric Control Angle Broom': ('Escoba angular con control eléctrico', 5), 'Blower': ('Soplador', 5),
 'Guardrail Cleaner': ('Limpiadora de defensas viales', 5), 'Guardrail translation machine': ('Desplazador de defensas viales', 5),
 'Beach cleaner': ('Limpiadora de arena', 5),
 'Brush Cutter': ('Desbrozadora', 6), 'Brush Cutter (2)': ('Desbrozadora de rotor', 6), 'Forest Mulcher': ('Trituradora forestal', 6),
 'Mower': ('Cortadora de césped', 6), 'Hedge Trimmer': ('Cortasetos', 6), 'Tree Saw': ('Sierra para árboles', 6),
 'High speed tree saw': ('Sierra de árboles de alta velocidad', 6), 'Tree Spade': ('Trasplantadora de árboles', 6), 'Tree Puller': ('Arrancador de árboles', 6),
 'Stump Grinder': ('Destoconadora', 6), 'Stump Bucket': ('Balde para tocones', 6), 'Chipper': ('Chipeadora de ramas', 6),
 'Soil Tiller': ('Rotocultivador', 6), 'Seeder': ('Sembradora', 6), 'Spreader': ('Esparcidora', 6),
 'Grapple Rake': ('Rastrillo con garra', 6), 'Heavy Grass Fork': ('Horquilla con garra para pasto', 6), 'Bale Fork': ('Horquilla para fardos', 6),
 'Soft Clamp': ('Pinza para fardos', 6), 'Haystack Reclamation Machine': ('Recolector de heno', 6),
 'Dung pushing device': ('Empujador de estiércol', 6), 'Simple manure pushing machine': ('Empujador de estiércol simple', 6),
 'Cattle in bed Ripper': ('Escarificador de cama de corral', 6),
 'Steel Tracks': ('Orugas de acero sobre neumáticos', 7), 'Rubber track outside tire': ('Orugas de goma sobre neumáticos', 7),
 'Tyre protection chain': ('Cadenas protectoras de neumáticos', 7), 'Rear Support': ('Estabilizadores traseros', 7),
 'Tilt-Tatch': ('Acople basculante (Tilt-Tatch)', 7), 'Automatic quick change rack': ('Placa de enganche rápido automático', 7),
}
