// GENERADO por tools/build-aditivos.py — no editar a mano
export interface Aditivo { slug: string; name: string; sub: string; desc: string; family: string; familyLabel: string; color: string; initials: string; kw: string[]; ficha: boolean }
export const ADITIVOS: Aditivo[] = [
 {
  "slug": "cq-accelera-pm-super",
  "name": "CQ ACCELERA PM SUPER",
  "sub": "",
  "desc": "",
  "family": "control-fraguado",
  "familyLabel": "Aceleradores y retardadores",
  "color": "#8B5CF6",
  "initials": "ACCELERA PM SUP…",
  "kw": [
   "calor",
   "verano",
   "frio",
   "invierno",
   "tiempo de trabajo",
   "transporte largo",
   "rapido",
   "lento",
   "accelera",
   "super",
   "acelerador",
   "agarre",
   "aditivo",
   "liquido",
   "libre",
   "cloruros",
   "listo",
   "consumo",
   "destinado",
   "acelerar",
   "fraguado",
   "hormigon",
   "dosis",
   "variar",
   "dependiendo",
   "necesidad",
   "aceleracion",
   "endurecimiento",
   "requerido",
   "desarrollado",
   "especialmente",
   "hormigones",
   "fluidos",
   "requieren",
   "altas",
   "resistencias",
   "iniciales",
   "desmolde",
   "cumple",
   "requisitos",
   "normas",
   "brasilenas",
   "clasificado",
   "resistencia",
   "principales",
   "ventajas",
   "aumenta",
   "desencofrado",
   "rapidos",
   "proporciona",
   "acabado",
   "losas",
   "provoca",
   "retraccion",
   "mango",
   "campos",
   "recomienda",
   "utilizar",
   "prefabricado",
   "armado"
  ],
  "ficha": true
 },
 {
  "slug": "cq-accelera-gunite",
  "name": "CQ Accelera Gunite",
  "sub": "",
  "desc": "CQ Accelera Gunite es un aditivo líquido de alto rendimiento, libre de cloruros, listo para usar, especialmente desarrollado para hormigón proyectado seco o húmedo. Su formulación proporciona aceleración de fraguado, mayor resistencia inicial y mayor eficienci",
  "family": "control-fraguado",
  "familyLabel": "Aceleradores y retardadores",
  "color": "#8B5CF6",
  "initials": "ACCELERA GUNITE",
  "kw": [
   "calor",
   "verano",
   "frio",
   "invierno",
   "tiempo de trabajo",
   "transporte largo",
   "rapido",
   "lento",
   "accelera",
   "gunite",
   "acelerador",
   "agarre",
   "hormigon",
   "proyectado",
   "aditivo",
   "liquido",
   "rendimiento",
   "libre",
   "cloruros",
   "listo",
   "consumir",
   "desarrollado",
   "especialmente",
   "humedo",
   "dosis",
   "variar",
   "segun",
   "necesidad",
   "aceleracion",
   "endurecimiento",
   "requerido",
   "cumple",
   "requisitos",
   "estandar",
   "brasilena",
   "clasificada",
   "principales",
   "ventajas",
   "aumenta",
   "resistencia",
   "inicial",
   "mayor",
   "compactacion",
   "capas",
   "disenadas",
   "aumentando",
   "impermeabilidad",
   "adherencia",
   "reduciendo",
   "reflexion",
   "perdida",
   "provoca",
   "retraccion",
   "mango",
   "permite",
   "gruesas",
   "productividad",
   "campos",
   "recomienda",
   "diferentes"
  ],
  "ficha": true
 },
 {
  "slug": "cq-accelera-pm",
  "name": "CQ Accelera PM",
  "sub": "Acelerador de agarre",
  "desc": "CQ Accelera PM es un aditivo líquido, libre de cloruros, listo para consumir, destinado a acelerar el fraguado. de hormigón. Su dosificación puede variar según la necesidad de aceleración y endurecimiento. requerido. Desarrollado especialmente para hormigones ",
  "family": "control-fraguado",
  "familyLabel": "Aceleradores y retardadores",
  "color": "#8B5CF6",
  "initials": "ACCELERA PM",
  "kw": [
   "calor",
   "verano",
   "frio",
   "invierno",
   "tiempo de trabajo",
   "transporte largo",
   "rapido",
   "lento",
   "accelera",
   "acelerador",
   "agarre",
   "aditivo",
   "liquido",
   "libre",
   "cloruros",
   "listo",
   "consumir",
   "destinado",
   "acelerar",
   "fraguado",
   "hormigon",
   "dosificacion",
   "variar",
   "segun",
   "necesidad",
   "aceleracion",
   "endurecimiento",
   "requerido",
   "desarrollado",
   "especialmente",
   "hormigones",
   "fluidos",
   "requieren",
   "altas",
   "resistencias",
   "iniciales",
   "desmolde",
   "cumple",
   "requisitos",
   "norma",
   "brasilena",
   "clasificada",
   "resistencia",
   "principales",
   "ventajas",
   "aumenta",
   "inicial",
   "desencofrado",
   "rapidos",
   "proporciona",
   "acabado",
   "losas",
   "provoca",
   "retraccion",
   "mango",
   "campos",
   "recomienda",
   "utilizar",
   "prefabricado",
   "armado"
  ],
  "ficha": true
 },
 {
  "slug": "cq-acryltop-hyper",
  "name": "CQ Acryltop Hyper",
  "sub": "Resina Acrílica",
  "desc": "CQ Acryltop Hyper es un barniz concentrado a base de agua, que cuando se aplica a la superficie forma una Película incolora y brillante, que mejora la impermeabilidad y la protección contra la lluvia y los rayos. UV, aumentando la resistencia al desgaste y fac",
  "family": "control-fraguado",
  "familyLabel": "Aceleradores y retardadores",
  "color": "#8B5CF6",
  "initials": "ACRYLTOP HYPER",
  "kw": [
   "calor",
   "verano",
   "frio",
   "invierno",
   "tiempo de trabajo",
   "transporte largo",
   "rapido",
   "lento",
   "acryltop",
   "hyper",
   "resina",
   "acrilica",
   "barniz",
   "concentrado",
   "aplica",
   "superficie",
   "forma",
   "pelicula",
   "incolora",
   "brillante",
   "mejora",
   "impermeabilidad",
   "proteccion",
   "contra",
   "lluvia",
   "rayos",
   "aumentando",
   "resistencia",
   "desgaste",
   "facilitando",
   "limpieza",
   "superficies",
   "facil",
   "secado",
   "principales",
   "ventajas",
   "inodoro",
   "aplicarse",
   "lugares",
   "ventilacion",
   "aspecto",
   "barrera",
   "humedad",
   "exterior",
   "aumenta",
   "durabilidad",
   "sustrato",
   "protege",
   "algas",
   "hongos",
   "previene",
   "eflorescencia",
   "campos",
   "recomienda",
   "fachadas",
   "hormigon",
   "visto",
   "baldosas",
   "mineral",
   "ladrillos"
  ],
  "ficha": true
 },
 {
  "slug": "cq-plast-stabilizer-23",
  "name": "CQ Plast Stabilizer 23",
  "sub": "Estabilizador de Hormigón",
  "desc": "CQ Plast Stabilizer 23 es un aditivo líquido, libre de cloruros, desarrollado para obtener un comportamiento más uniforme y predecible en hormigones de alto rendimiento. Aumenta el tiempo de fraguado controlando la hidratación del cemento y facilitando las ope",
  "family": "control-fraguado",
  "familyLabel": "Aceleradores y retardadores",
  "color": "#8B5CF6",
  "initials": "PLAST STABILIZE…",
  "kw": [
   "calor",
   "verano",
   "frio",
   "invierno",
   "tiempo de trabajo",
   "transporte largo",
   "rapido",
   "lento",
   "plast",
   "stabilizer",
   "estabilizador",
   "hormigon",
   "aditivo",
   "liquido",
   "libre",
   "cloruros",
   "desarrollado",
   "obtener",
   "comportamiento",
   "uniforme",
   "predecible",
   "desempeno",
   "aumenta",
   "tiempo",
   "fraguado",
   "controlar",
   "hidratacion",
   "cemento",
   "facilitar",
   "operaciones",
   "acabado",
   "cumple",
   "requisitos",
   "norma",
   "brasilena",
   "clasificada",
   "controller",
   "principales",
   "ventajas",
   "reduce",
   "contenido",
   "necesario",
   "determinada",
   "trabajabilidad",
   "promueve",
   "retrasos",
   "extensos",
   "moderados",
   "mejora",
   "reduccion",
   "segregacion",
   "compensa",
   "efectos",
   "perdida",
   "asentamiento",
   "debido",
   "retraso",
   "mezclado",
   "colocacion",
   "desperdicio"
  ],
  "ficha": true
 },
 {
  "slug": "cq-stable-c",
  "name": "CQ Stable C",
  "sub": "",
  "desc": "CQ Stable C es un aditivo líquido, libre de cloruros, desarrollado para actuar como plastificante, retardante y estabilizador en morteros. Además de aumentar la trabajabilidad del mortero, CQ Stable C controla la hidratación del cemento hasta por 72 horas, fac",
  "family": "control-fraguado",
  "familyLabel": "Aceleradores y retardadores",
  "color": "#8B5CF6",
  "initials": "STABLE C",
  "kw": [
   "calor",
   "verano",
   "frio",
   "invierno",
   "tiempo de trabajo",
   "transporte largo",
   "rapido",
   "lento",
   "stable",
   "aditivo",
   "plastificante",
   "estabilizante",
   "morteros",
   "liquido",
   "libre",
   "cloruros",
   "desarrollado",
   "retardante",
   "estabilizador",
   "ademas",
   "aumentar",
   "trabajabilidad",
   "mortero",
   "controla",
   "hidratacion",
   "cemento",
   "horas",
   "facilitando",
   "operaciones",
   "acabado",
   "proporcionando",
   "ahorro",
   "material",
   "agilidad",
   "cumple",
   "requisitos",
   "estandar",
   "brasilena",
   "clasificada",
   "controlador",
   "principales",
   "ventajas",
   "mayor",
   "adherencia",
   "cohesion",
   "ausencia",
   "grietas",
   "menor",
   "exudacion",
   "reduce",
   "friccion",
   "particulas",
   "reduciendo",
   "amasado",
   "requerida",
   "produce",
   "efecto",
   "manteniendo",
   "tiempo",
   "durabilidad"
  ],
  "ficha": true
 },
 {
  "slug": "cq-curamix-ac",
  "name": "CQ Curamix AC",
  "sub": "Agente curativo",
  "desc": "CQ Curamix AC es un producto líquido a base de agua que mejora el curado del hormigón. Se aplica a la Superficie de hormigón fresco que forma una película uniforme, evitando la evaporación repentina del agua. mezcla de hormigón. De esta forma, el hormigón comp",
  "family": "cura",
  "familyLabel": "Cura del concreto",
  "color": "#22C55E",
  "initials": "CURAMIX AC",
  "kw": [
   "curado",
   "secado",
   "proteccion",
   "sol",
   "viento",
   "evaporacion",
   "curamix",
   "agente",
   "curativo",
   "liquido",
   "mejora",
   "hormigon",
   "aplica",
   "superficie",
   "fresco",
   "forma",
   "pelicula",
   "uniforme",
   "evitando",
   "repentina",
   "mezcla",
   "completa",
   "proceso",
   "mayor",
   "humedad",
   "posible",
   "correcta",
   "hidratacion",
   "cemento",
   "principales",
   "ventajas",
   "facil",
   "protege",
   "climas",
   "calidos",
   "calurosos",
   "permite",
   "mejor",
   "reduce",
   "formacion",
   "grietas",
   "contraccion",
   "aumenta",
   "durabilidad",
   "campos",
   "recomienda",
   "hormigones",
   "expuesta",
   "tales",
   "losas",
   "pavimentos",
   "prefabricados",
   "datos",
   "tecnicos",
   "funcion",
   "embalaje",
   "vende",
   "acrilica",
   "aspecto",
   "blanco"
  ],
  "ficha": true
 },
 {
  "slug": "cq-curamix-pm",
  "name": "CQ Curamix PM",
  "sub": "Agente curativo",
  "desc": "CQ Curamix PM es un producto líquido a base de agua que mejora el curado del hormigón. Se aplica a la Superficie de hormigón fresco que forma una película uniforme, evitando la evaporación repentina del agua. mezcla de hormigón. De esta forma, el hormigón comp",
  "family": "cura",
  "familyLabel": "Cura del concreto",
  "color": "#22C55E",
  "initials": "CURAMIX PM",
  "kw": [
   "curado",
   "secado",
   "proteccion",
   "sol",
   "viento",
   "evaporacion",
   "curamix",
   "agente",
   "curativo",
   "liquido",
   "mejora",
   "hormigon",
   "aplica",
   "superficie",
   "fresco",
   "forma",
   "pelicula",
   "uniforme",
   "evitando",
   "repentina",
   "mezcla",
   "completa",
   "proceso",
   "mayor",
   "humedad",
   "posible",
   "correcta",
   "hidratacion",
   "cemento",
   "principales",
   "ventajas",
   "facil",
   "aplicarse",
   "areas",
   "internas",
   "externas",
   "protege",
   "climas",
   "calidos",
   "calurosos",
   "permite",
   "mejor",
   "reduce",
   "formacion",
   "grietas",
   "contraccion",
   "aumenta",
   "durabilidad",
   "campos",
   "recomienda",
   "hormigones",
   "expuesta",
   "tales",
   "losas",
   "pavimentos",
   "prefabricados",
   "datos",
   "tecnicos",
   "funcion",
   "embalaje"
  ],
  "ficha": true
 },
 {
  "slug": "maturix",
  "name": "Tecnologías - Maturix",
  "sub": "",
  "desc": "Maturix es un sistema inteligente de monitoreo de hormigón que utiliza sensores inalámbricos para proporcionar datos precisos en tiempo real directamente desde el interior de la estructura, lo que permite un control total del proceso de curado y secado.",
  "family": "cura",
  "familyLabel": "Cura del concreto",
  "color": "#22C55E",
  "initials": "TECNOLOGÍAS - M…",
  "kw": [
   "curado",
   "secado",
   "proteccion",
   "sol",
   "viento",
   "evaporacion",
   "tecnologias",
   "maturix",
   "precisa",
   "temperatura",
   "monitoreo",
   "inteligente",
   "hormigon",
   "tiempo",
   "sistema",
   "inalambrico",
   "sensores",
   "remoto",
   "proyectos",
   "mundo",
   "datos",
   "inalambricos",
   "proporcionar",
   "precisos",
   "directamente",
   "interior",
   "estructura",
   "permite",
   "control",
   "total",
   "proceso",
   "recopilacion",
   "remota",
   "recopilados",
   "rapidamente",
   "guardados",
   "automaticamente",
   "informes",
   "linea",
   "facil",
   "acceso",
   "documentacion",
   "digital",
   "calidad",
   "fines",
   "legales",
   "deteccion",
   "temprana",
   "problemas",
   "identifica",
   "pequenos",
   "cambios",
   "propiedades",
   "detecta",
   "grietas",
   "debilitamientos",
   "vuelvan",
   "criticos",
   "intervencion",
   "mejor"
  ],
  "ficha": false
 },
 {
  "slug": "cq-desform-a-435",
  "name": "CQ Desform A 435",
  "sub": "",
  "desc": "CQ Desform A 435 es una composición oleosa fina emulsionada en agua, cuyo objetivo es evitar la adherencia del hormigón sobre los encofrados, facilitando el desmolde y asegurando una mejor calidad del Acabado superficial del hormigón.",
  "family": "desmoldantes",
  "familyLabel": "Desmoldantes",
  "color": "#64748B",
  "initials": "DESFORM A 435",
  "kw": [
   "molde",
   "encofrado",
   "desmolde",
   "formaleta",
   "prefabricado",
   "desform",
   "435",
   "desformar",
   "agente",
   "desmoldante",
   "composicion",
   "oleosa",
   "emulsionada",
   "objetivo",
   "evitar",
   "adherencia",
   "hormigon",
   "encofrados",
   "facilitando",
   "asegurando",
   "mejor",
   "calidad",
   "acabado",
   "superficial",
   "propiedades",
   "aplica",
   "correctamente",
   "evita",
   "adhiera",
   "permitiendo",
   "obtener",
   "visto",
   "aplicar",
   "mantener",
   "formas",
   "lugar",
   "protegido",
   "lluvia",
   "campos",
   "recomienda",
   "metal",
   "plastico",
   "madera",
   "proposito",
   "producir",
   "expuesto",
   "piezas",
   "prefabricadas",
   "general",
   "necesaria",
   "buena",
   "apariencia",
   "datos",
   "tecnicos",
   "funcion",
   "liberacion",
   "embalaje",
   "aceites",
   "emulsionados",
   "vendido"
  ],
  "ficha": true
 },
 {
  "slug": "cq-desform-eco-450",
  "name": "CQ Desform Eco 450",
  "sub": "Agente de liberación",
  "desc": "CQ Desform Eco 450 es un desmoldeante de base vegetal, listo para consumir, biodegradable, formado por una fina composición oleosa, cuyo objetivo es evitar que el hormigón se adhiera a los encofrados, facilitando la desmoldear y asegurar una mejor calidad del ",
  "family": "desmoldantes",
  "familyLabel": "Desmoldantes",
  "color": "#64748B",
  "initials": "DESFORM ECO 450",
  "kw": [
   "molde",
   "encofrado",
   "desmolde",
   "formaleta",
   "prefabricado",
   "desform",
   "eco",
   "450",
   "agente",
   "liberacion",
   "desmoldeante",
   "vegetal",
   "listo",
   "consumir",
   "biodegradable",
   "formado",
   "composicion",
   "oleosa",
   "objetivo",
   "evitar",
   "hormigon",
   "adhiera",
   "encofrados",
   "facilitando",
   "desmoldear",
   "asegurar",
   "mejor",
   "calidad",
   "acabado",
   "superficial",
   "propiedades",
   "mejora",
   "apariencia",
   "reduce",
   "tiempo",
   "preparacion",
   "protege",
   "superficies",
   "moldes",
   "aumentando",
   "tiene",
   "antidesgaste",
   "antioxidantes",
   "facil",
   "rendimiento",
   "campos",
   "utilizar",
   "metal",
   "madera",
   "formas",
   "resinadas",
   "plastificadas",
   "datos",
   "tecnicos",
   "funcion",
   "embalaje",
   "aceites",
   "vegetales",
   "comercializados",
   "bidones"
  ],
  "ficha": true
 },
 {
  "slug": "cq-desform-eco-s-30",
  "name": "CQ Desform Eco S 30",
  "sub": "Agente desmoldante biodegradable",
  "desc": "CQ Desform Eco S 30 es un desmoldante biodegradable listo para usar. De estructura aceitosa fino, evita que el hormigón se adhiera al encofrado, favoreciendo el desmolde y mejorando el acabado superficie de la pieza. CQ Desform Eco S 30 es biodegradable y segu",
  "family": "desmoldantes",
  "familyLabel": "Desmoldantes",
  "color": "#64748B",
  "initials": "DESFORM ECO S 30",
  "kw": [
   "molde",
   "encofrado",
   "desmolde",
   "formaleta",
   "prefabricado",
   "desform",
   "eco",
   "agente",
   "desmoldante",
   "biodegradable",
   "listo",
   "estructura",
   "aceitosa",
   "evita",
   "hormigon",
   "adhiera",
   "favoreciendo",
   "mejorando",
   "acabado",
   "superficie",
   "pieza",
   "seguro",
   "medio",
   "ambiente",
   "propiedades",
   "facilita",
   "mejora",
   "apariencia",
   "superficial",
   "reduce",
   "tiempo",
   "preparacion",
   "protege",
   "superficies",
   "moldes",
   "aumentando",
   "tiene",
   "antidesgaste",
   "facil",
   "rendimiento",
   "previene",
   "danos",
   "ambientales",
   "elimina",
   "costes",
   "nocivos",
   "salud",
   "datos",
   "tecnicos",
   "funcion",
   "embalaje",
   "aceites",
   "vegetales",
   "comercializados",
   "aspecto",
   "liquido",
   "amarillo",
   "bidones",
   "contenedor",
   "viscosidad"
  ],
  "ficha": true
 },
 {
  "slug": "cq-desform-eco-s-60",
  "name": "CQ Desform Eco S 60",
  "sub": "",
  "desc": "CQ Desform Eco S 60 es un desmoldante biodegradable listo para usar. Con una estructura fina capa oleosa, impide que el hormigón se adhiera al encofrado, favoreciendo el desmolde y mejorando el acabado superficial de la pieza. CQ Desform Eco S 60 es biodegrada",
  "family": "desmoldantes",
  "familyLabel": "Desmoldantes",
  "color": "#64748B",
  "initials": "DESFORM ECO S 60",
  "kw": [
   "molde",
   "encofrado",
   "desmolde",
   "formaleta",
   "prefabricado",
   "desform",
   "eco",
   "agente",
   "liberacion",
   "biodegradable",
   "desmoldante",
   "listo",
   "estructura",
   "oleosa",
   "impide",
   "hormigon",
   "adhiera",
   "favoreciendo",
   "mejorando",
   "acabado",
   "superficial",
   "pieza",
   "seguro",
   "medio",
   "ambiente",
   "propiedades",
   "facilita",
   "mejora",
   "apariencia",
   "reduce",
   "tiempo",
   "preparacion",
   "protege",
   "superficies",
   "moldes",
   "aumentando",
   "tiene",
   "antidesgaste",
   "facil",
   "rendimiento",
   "formas",
   "metalicas",
   "previene",
   "danos",
   "ambientales",
   "elimina",
   "costes",
   "sanitarios",
   "datos",
   "tecnicos",
   "funcion",
   "embalaje",
   "aceites",
   "vegetales",
   "vendido",
   "aspecto",
   "liquido",
   "amarillo",
   "viscosidad",
   "bidon"
  ],
  "ficha": true
 },
 {
  "slug": "cq-desform-n-60",
  "name": "CQ Desform N 60",
  "sub": "Agente de liberación",
  "desc": "CQ Desform N 60 es un desmoldeante de base vegetal y mineral, listo para el consumo, formado por un composición fina oleosa, cuyo objetivo es evitar que el hormigón se adhiera a los encofrados, facilitando la desmoldear y asegurar una mejor calidad del acabado",
  "family": "desmoldantes",
  "familyLabel": "Desmoldantes",
  "color": "#64748B",
  "initials": "DESFORM N 60",
  "kw": [
   "molde",
   "encofrado",
   "desmolde",
   "formaleta",
   "prefabricado",
   "desform",
   "agente",
   "liberacion",
   "desmoldeante",
   "vegetal",
   "mineral",
   "listo",
   "consumo",
   "formado",
   "composicion",
   "oleosa",
   "objetivo",
   "evitar",
   "hormigon",
   "adhiera",
   "encofrados",
   "facilitando",
   "desmoldear",
   "asegurar",
   "mejor",
   "calidad",
   "acabado",
   "superficial",
   "propiedades",
   "facilita",
   "mejora",
   "apariencia",
   "reduce",
   "tiempo",
   "preparacion",
   "protege",
   "superficies",
   "moldes",
   "aumentando",
   "tiene",
   "antidesgaste",
   "antioxidantes",
   "facil",
   "rendimiento",
   "campos",
   "utilizar",
   "madera",
   "metalicos",
   "resinados",
   "plastificados",
   "datos",
   "tecnicos",
   "funcion",
   "embalaje",
   "aceites",
   "vegetales",
   "minerales",
   "vendidos",
   "bidones",
   "aspecto"
  ],
  "ficha": true
 },
 {
  "slug": "cq-compenser",
  "name": "CQ Compenser",
  "sub": "Aditivo Compensador de Contracción para Hormigón",
  "desc": "CQ Compenser es un aditivo en polvo multifuncional, compuesto por óxido de calcio supercalcinado, tratado térmicamente y con una selección de gránulos. Fue desarrollado para pisos y pavimentos de hormigón de cemento Portland, promoviendo una estabilidad volumé",
  "family": "otros",
  "familyLabel": "Especialidades",
  "color": "#A78BFA",
  "initials": "COMPENSER",
  "kw": [
   "compenser",
   "aditivo",
   "compensador",
   "contraccion",
   "hormigon",
   "polvo",
   "multifuncional",
   "compuesto",
   "oxido",
   "calcio",
   "supercalcinado",
   "tratado",
   "termicamente",
   "seleccion",
   "granulados",
   "especialmente",
   "desarrollado",
   "pavimentos",
   "pisos",
   "cemento",
   "portland",
   "tiene",
   "funcion",
   "controlar",
   "retraccion",
   "preparacion",
   "fisuras",
   "promoviendo",
   "mayor",
   "durabilidad",
   "tamano",
   "industriales",
   "placas",
   "juntas",
   "jointless",
   "actuacion",
   "consiste",
   "estabilidad",
   "volumetrica",
   "controlada",
   "modulacion",
   "inicial",
   "expansion",
   "oponiendose",
   "largo",
   "plazo",
   "formulacion",
   "prepara",
   "materias",
   "primas",
   "inorganicas",
   "libres",
   "cloruros",
   "sulfoaluminatos",
   "otras",
   "sustancias",
   "nocivas",
   "principales",
   "ventajas",
   "reduce"
  ],
  "ficha": true
 },
 {
  "slug": "cq-compenser-501",
  "name": "CQ Compenser 501",
  "sub": "",
  "desc": "CQ COMPENSER 501 es un aditivo en polvo libre de cloruros, sulfoaluminatos y otros componentes. perjudicial para el hormigón, que tiene control de retracción y se utiliza para preparar hormigón sin grieta, rellenando completamente los espacios vacíos, lo que f",
  "family": "otros",
  "familyLabel": "Especialidades",
  "color": "#A78BFA",
  "initials": "COMPENSER 501",
  "kw": [
   "compenser",
   "501",
   "compensador",
   "retraccion",
   "aditivo",
   "polvo",
   "libre",
   "cloruros",
   "sulfoaluminatos",
   "otros",
   "componentes",
   "perjudicial",
   "hormigon",
   "tiene",
   "control",
   "preparar",
   "grieta",
   "rellenando",
   "completamente",
   "espacios",
   "vacios",
   "facilita",
   "grietas",
   "confinado",
   "principales",
   "ventajas",
   "elimina",
   "contraccion",
   "reduce",
   "aberturas",
   "articulaciones",
   "relleno",
   "platos",
   "grandes",
   "campos",
   "pisos",
   "industriales",
   "prefabricado",
   "muros",
   "losas",
   "datos",
   "tecnicos",
   "embalaje",
   "cargas",
   "minerales",
   "vendido",
   "aspecto",
   "blanco",
   "sacos",
   "kilos",
   "consumo",
   "aproximado",
   "dosis",
   "varian",
   "cemento",
   "metodo",
   "junto",
   "aridos",
   "directamente",
   "secuencia"
  ],
  "ficha": true
 },
 {
  "slug": "cq-sil-55",
  "name": "CQ Sil 55",
  "sub": "",
  "desc": "CQ SIL 55 es una emulsión de humos de sílice, lista para el consumo, libre de cloruros y compatible con distintos tipos de cemento. Proporciona muy alta reactividad con los compuestos formados a partir de la hidratación del cemento, proporcionando mejores comp",
  "family": "otros",
  "familyLabel": "Especialidades",
  "color": "#A78BFA",
  "initials": "SIL 55",
  "kw": [
   "sil",
   "silice",
   "liquida",
   "emulsion",
   "humos",
   "lista",
   "consumo",
   "libre",
   "cloruros",
   "compatible",
   "diferentes",
   "tipos",
   "cemento",
   "proporciona",
   "reactividad",
   "compuestos",
   "formados",
   "partir",
   "hidratacion",
   "proporcionando",
   "mejor",
   "comportamiento",
   "hormigones",
   "morteros",
   "principales",
   "ventajas",
   "aumenta",
   "resistencia",
   "inicial",
   "final",
   "compresion",
   "traccion",
   "mejora",
   "cohesion",
   "consecuencia",
   "reduce",
   "manifestaciones",
   "exudacion",
   "segregacion",
   "impermeabilidad",
   "durabilidad",
   "hormigon",
   "ambientes",
   "agresivos",
   "ataques",
   "quimicos",
   "iones",
   "cloruro",
   "adherencia",
   "armaduras",
   "campos",
   "recomendado",
   "tales",
   "dosificado",
   "plantas",
   "suelos",
   "industriales",
   "autocompactante",
   "pavimento",
   "rigido"
  ],
  "ficha": true
 },
 {
  "slug": "authenty-piso",
  "name": "Tecnologías",
  "sub": "",
  "desc": "En alianza con Authenty, Camargo Química ofrece un completo software de gestión del proceso de producción de pisos. Una herramienta innovadora que va más allá del dimensionamiento, incluyendo el cálculo de dosis, la gestión de precios y la optimización de todo",
  "family": "otros",
  "familyLabel": "Especialidades",
  "color": "#A78BFA",
  "initials": "TECNOLOGÍAS",
  "kw": [
   "tecnologias",
   "software",
   "dimensionamiento",
   "pisos",
   "hormigon",
   "authenty",
   "facilidad",
   "seguridad",
   "gestion",
   "completa",
   "calculo",
   "dosificacion",
   "precio",
   "mucho",
   "proyecto",
   "suelo",
   "tecnologia",
   "precision",
   "alianza",
   "ofrece",
   "completo",
   "proceso",
   "produccion",
   "herramienta",
   "innovadora",
   "incluyendo",
   "dosis",
   "precios",
   "optimizacion",
   "productivo",
   "estructural",
   "preciso",
   "interfaz",
   "intuitiva",
   "visual",
   "resultados",
   "tiempo",
   "manejo",
   "control",
   "trazas",
   "formulacion",
   "materiales",
   "automatico",
   "consumo",
   "costos",
   "cotizaciones",
   "automatizadas",
   "comparacion",
   "soluciones",
   "optimizado",
   "cantidades",
   "precisas",
   "documentacion",
   "recomienda",
   "multiples",
   "campos",
   "industriales",
   "dimensionado",
   "industrias",
   "centros"
  ],
  "ficha": false
 },
 {
  "slug": "cq-fiber-54",
  "name": "CQ Fiber 54",
  "sub": "",
  "desc": "CQ Fiber 54 es una fibra sintética estructural de altas prestaciones, desarrollada específicamente para refuerzo de hormigón en suelos industriales, pavimentos rígidos y prefabricados. Debido al alto contenido de filamentos por kilogramo, su uso permite un efi",
  "family": "fibras",
  "familyLabel": "Fibras",
  "color": "#F59E0B",
  "initials": "FIBER 54",
  "kw": [
   "fisura",
   "grieta",
   "rajadura",
   "retraccion",
   "malla",
   "refuerzo",
   "fiber",
   "fibra",
   "sintetica",
   "estructural",
   "rendimiento",
   "desarrollada",
   "sustituir",
   "mamparas",
   "fibras",
   "soldadas",
   "acero",
   "debido",
   "contenido",
   "filamentos",
   "kilogramo",
   "permite",
   "reforzar",
   "propiedades",
   "estructurales",
   "hormigon",
   "aumentando",
   "resistencia",
   "mecanica",
   "cumple",
   "criterios",
   "principales",
   "ventajas",
   "ahorro",
   "comparacion",
   "mallas",
   "metalicas",
   "mejor",
   "acabado",
   "afloramientos",
   "superficiales",
   "garantiza",
   "mayor",
   "tenacidad",
   "resistente",
   "alcalinidad",
   "crack",
   "aumento",
   "reduccion",
   "patologias",
   "exudacion",
   "microfisuras",
   "practicidad",
   "campos",
   "recomendado",
   "pisos",
   "industriales",
   "rigidos",
   "elementos",
   "prefabricados"
  ],
  "ficha": true
 },
 {
  "slug": "cq-fiber-54-plus",
  "name": "CQ Fiber 54 Plus",
  "sub": "",
  "desc": "CQ FIBER 54 Plus es una fibra sintética estructural de alto rendimiento, desarrollada para reemplazar Mallas electrosoldadas y fibras de acero. Debido al alto contenido de filamentos por kilogramo, su uso permite un refuerzo estructural al hormigón, aumentando",
  "family": "fibras",
  "familyLabel": "Fibras",
  "color": "#F59E0B",
  "initials": "FIBER 54 PLUS",
  "kw": [
   "fisura",
   "grieta",
   "rajadura",
   "retraccion",
   "malla",
   "refuerzo",
   "fiber",
   "plus",
   "fibra",
   "sintetica",
   "estructural",
   "rendimiento",
   "desarrollada",
   "reemplazar",
   "mallas",
   "electrosoldadas",
   "fibras",
   "acero",
   "debido",
   "contenido",
   "filamentos",
   "kilogramo",
   "permite",
   "hormigon",
   "aumentando",
   "resistencia",
   "mecanica",
   "cumple",
   "criterios",
   "principales",
   "ventajas",
   "ahorros",
   "respecto",
   "metalicas",
   "mejor",
   "acabado",
   "afloramientos",
   "superficiales",
   "asegura",
   "mayor",
   "tenacidad",
   "resistente",
   "alcalinidad",
   "crack",
   "aumento",
   "reduccion",
   "patologias",
   "exudacion",
   "microfisuracion",
   "practicidad",
   "ahorro",
   "campos",
   "pisos",
   "industriales",
   "suelos",
   "duros",
   "elementos",
   "prefabricados",
   "capas",
   "compresion"
  ],
  "ficha": true
 },
 {
  "slug": "cq-macro-fiber-twisted-54",
  "name": "CQ Macro Fiber Twisted 54",
  "sub": "",
  "desc": "CQ Macro Fiber Twisted es una fibra sintética estructural de alto rendimiento desarrollada especialmente para hormigón reforzado con fibra (FRC). Su diferencia radica en su anclaje mecánico a torsión, que mejora significativamente la adherencia a la matriz de ",
  "family": "fibras",
  "familyLabel": "Fibras",
  "color": "#F59E0B",
  "initials": "MACRO FIBER TWI…",
  "kw": [
   "fisura",
   "grieta",
   "rajadura",
   "retraccion",
   "malla",
   "refuerzo",
   "macro",
   "fiber",
   "twisted",
   "fibras",
   "fibra",
   "sintetica",
   "estructural",
   "anclaje",
   "torsional",
   "agarre",
   "mecanico",
   "superior",
   "tridimensional",
   "dificulta",
   "propagacion",
   "grietas",
   "reduce",
   "costos",
   "operativos",
   "aumenta",
   "durabilidad",
   "tecnologia",
   "rendimiento",
   "desarrollada",
   "especialmente",
   "hormigon",
   "reforzado",
   "diferencia",
   "radica",
   "torsion",
   "mejora",
   "significativamente",
   "adherencia",
   "matriz",
   "debido",
   "contenido",
   "filamentos",
   "kilogramo",
   "permite",
   "eficaz",
   "aumentando",
   "resistencia",
   "mecanica",
   "dificultando",
   "adhesion",
   "mejor",
   "transferencia",
   "tensiones",
   "mayor",
   "eficiencia",
   "distribucion",
   "control",
   "multidireccional",
   "cobertura"
  ],
  "ficha": false
 },
 {
  "slug": "cq-micro-fiber",
  "name": "CQ Micro Fiber",
  "sub": "",
  "desc": "CQ Micro Fiber es una fibra de polipropileno multifilamento ultrafina que se dispersa fácil y rápidamente en la mezcla de hormigón. Proporciona refuerzo multidireccional en toda la masa, mejora las cualidades mecánicas y aumenta significativamente la durabilid",
  "family": "fibras",
  "familyLabel": "Fibras",
  "color": "#F59E0B",
  "initials": "MICRO FIBER",
  "kw": [
   "fisura",
   "grieta",
   "rajadura",
   "retraccion",
   "malla",
   "refuerzo",
   "micro",
   "fiber",
   "fibra",
   "emitida",
   "polipropileno",
   "material",
   "multifilamento",
   "compatible",
   "cementos",
   "dispersa",
   "facil",
   "rapidamente",
   "mezcla",
   "hormigon",
   "proporciona",
   "multidireccional",
   "mejora",
   "cualidades",
   "mecanicas",
   "aumenta",
   "durabilidad",
   "principales",
   "ventajas",
   "afecta",
   "trabajabilidad",
   "cohesion",
   "todos",
   "aditivos",
   "reduce",
   "contraccion",
   "plastico",
   "excelente",
   "dispersion",
   "proporcionando",
   "tridimensional",
   "contra",
   "efecto",
   "agrietamiento",
   "sustituir",
   "acero",
   "piezas",
   "estructurales",
   "migracion",
   "resistencia",
   "impacto",
   "abrasion",
   "fuego",
   "resistente",
   "acidos",
   "alcalis",
   "previene",
   "oxidacion",
   "deterioro",
   "congelamiento"
  ],
  "ficha": true
 },
 {
  "slug": "cq-robust-79",
  "name": "CQ Robust 79",
  "sub": "",
  "desc": "CQ Robust 79 está compuesto por aditivos superplastificantes de tercera generación a base de policarboxilato, Listo para el consumo, completamente libre de cloruros y compatible con distintos tipos de cemento. puede Reducir hasta un 12% del agua de amasado, de",
  "family": "fibras",
  "familyLabel": "Fibras",
  "color": "#F59E0B",
  "initials": "ROBUST 79",
  "kw": [
   "fisura",
   "grieta",
   "rajadura",
   "retraccion",
   "malla",
   "refuerzo",
   "robust",
   "robusto",
   "superplastificante",
   "compuesto",
   "aditivos",
   "superplastificantes",
   "tercera",
   "generacion",
   "policarboxilato",
   "listo",
   "consumo",
   "completamente",
   "libre",
   "cloruros",
   "compatible",
   "distintos",
   "tipos",
   "cemento",
   "reducir",
   "amasado",
   "dependiendo",
   "dosificacion",
   "mezcla",
   "caracteristicas",
   "materiales",
   "usado",
   "dosis",
   "habitual",
   "varia",
   "portland",
   "cumple",
   "requisitos",
   "norma",
   "brasilena",
   "clasificado",
   "reductor",
   "principales",
   "ventajas",
   "mayor",
   "resistencia",
   "todas",
   "edades",
   "aumento",
   "asentamiento",
   "trabajabilidad",
   "reduccion",
   "contraccion",
   "agrietamiento",
   "facilita",
   "bombeo",
   "lanzamiento",
   "compactacion",
   "facilidad",
   "acabado"
  ],
  "ficha": true
 },
 {
  "slug": "cq-robust-81",
  "name": "CQ Robust 81",
  "sub": "",
  "desc": "CQ Robust 81 está compuesto por aditivos superplastificantes de tercera generación a base de policarboxilato, Listo para el consumo, completamente libre de cloruros y compatible con distintos tipos de cemento. puede Reducir hasta un 12% del agua de amasado, de",
  "family": "fibras",
  "familyLabel": "Fibras",
  "color": "#F59E0B",
  "initials": "ROBUST 81",
  "kw": [
   "fisura",
   "grieta",
   "rajadura",
   "retraccion",
   "malla",
   "refuerzo",
   "robust",
   "robusto",
   "superplastificante",
   "compuesto",
   "aditivos",
   "superplastificantes",
   "tercera",
   "generacion",
   "policarboxilato",
   "listo",
   "consumo",
   "completamente",
   "libre",
   "cloruros",
   "compatible",
   "distintos",
   "tipos",
   "cemento",
   "reducir",
   "amasado",
   "dependiendo",
   "dosificacion",
   "mezcla",
   "caracteristicas",
   "materiales",
   "usado",
   "dosis",
   "habitual",
   "varia",
   "todos",
   "portland",
   "cumple",
   "requisitos",
   "norma",
   "brasilena",
   "clasificado",
   "reductor",
   "principales",
   "ventajas",
   "mayor",
   "resistencia",
   "todas",
   "edades",
   "aumento",
   "asentamiento",
   "trabajabilidad",
   "reduccion",
   "contraccion",
   "agrietamiento",
   "facilita",
   "bombeo",
   "lanzamiento",
   "consolidacion",
   "acabado"
  ],
  "ficha": true
 },
 {
  "slug": "cq-admix-mv-100",
  "name": "CQ Admix MV 100",
  "sub": "Modificador de Viscosidad",
  "desc": "CQ Admix MV 100 es un aditivo modificador de la viscosidad para hormigones y morteros, que cambia la características reológicas de la mezcla, evitando la segregación. Cumple con los requisitos de las normas brasileñas NBR 11768-1, clasificado como MV-AS (Modif",
  "family": "impermeabilizantes",
  "familyLabel": "Impermeabilizantes",
  "color": "#14B8A6",
  "initials": "ADMIX MV 100",
  "kw": [
   "humedad",
   "infiltracion",
   "filtracion",
   "goteras",
   "estanqueidad",
   "tanque",
   "cisterna",
   "subsuelo",
   "admix",
   "100",
   "modificador",
   "viscosidad",
   "aditivo",
   "hormigones",
   "morteros",
   "cambia",
   "caracteristicas",
   "reologicas",
   "mezcla",
   "evitando",
   "segregacion",
   "cumple",
   "requisitos",
   "normas",
   "brasilenas",
   "clasificado",
   "antisegregante",
   "principales",
   "ventajas",
   "mayor",
   "cohesion",
   "consiguiente",
   "reduccion",
   "manifestaciones",
   "reduce",
   "exudacion",
   "mejora",
   "bombeo",
   "colocacion",
   "hormigon",
   "corrige",
   "falta",
   "materiales",
   "finos",
   "linea",
   "campos",
   "recomienda",
   "dosificado",
   "plantas",
   "suelos",
   "industriales",
   "autocompactante",
   "visto",
   "datos",
   "tecnicos",
   "embalaje",
   "funcion",
   "modificadora",
   "emulsion",
   "polimerica"
  ],
  "ficha": true
 },
 {
  "slug": "cq-admix-n-20",
  "name": "CQ Admix N 20",
  "sub": "Desintegrador de Aire para Hormigón",
  "desc": "CQ ADMIX N 20 es un aditivo desincorporador de aire para hormigón listo para su consumo, formulado con antiespumantes especiales, compatible con diferentes tipos de cemento y libre de cloruros. Favorece la desincorporación instantánea del aire en hormigones y ",
  "family": "impermeabilizantes",
  "familyLabel": "Impermeabilizantes",
  "color": "#14B8A6",
  "initials": "ADMIX N 20",
  "kw": [
   "humedad",
   "infiltracion",
   "filtracion",
   "goteras",
   "estanqueidad",
   "tanque",
   "cisterna",
   "subsuelo",
   "admix",
   "desintegrador",
   "hormigon",
   "aditivo",
   "modificador",
   "viscosidad",
   "hormigones",
   "morteros",
   "cambia",
   "caracteristicas",
   "reologicas",
   "mezcla",
   "evitando",
   "segregacion",
   "cumple",
   "requisitos",
   "normas",
   "brasilenas",
   "clasificado",
   "antisegregante",
   "principales",
   "ventajas",
   "tiempo",
   "fraguado",
   "aumenta",
   "cohesion",
   "homogeneidad",
   "mejora",
   "trabajabilidad",
   "apariencia",
   "superficial",
   "campos",
   "recomienda",
   "problema",
   "atrapado",
   "fluido",
   "bombeado",
   "ligero",
   "premoldeado",
   "visto",
   "datos",
   "tecnicos",
   "funcion",
   "desentrenador",
   "embalaje",
   "comercializa",
   "antiespumante",
   "aspecto",
   "liquido",
   "blanco",
   "contenedor",
   "densidad"
  ],
  "ficha": true
 },
 {
  "slug": "cq-green-seal",
  "name": "CQ Green Seal",
  "sub": "",
  "desc": "Manta de poliuretano líquido 100% sólidos, bicomponente, elástica y flexible. Adherente a los más diversos sustratos encontrados en la construcción civil, permitiendo impermeabilización estanca y alta resistencia a la corrosión, abrasión, intemperie y sustanci",
  "family": "impermeabilizantes",
  "familyLabel": "Impermeabilizantes",
  "color": "#14B8A6",
  "initials": "GREEN SEAL",
  "kw": [
   "humedad",
   "infiltracion",
   "filtracion",
   "goteras",
   "estanqueidad",
   "tanque",
   "cisterna",
   "subsuelo",
   "green",
   "seal",
   "manta",
   "liquida",
   "poliuretano",
   "liquido",
   "solidos",
   "bicomponente",
   "elastica",
   "flexible",
   "adherente",
   "diferentes",
   "sustratos",
   "encuentran",
   "construccion",
   "civil",
   "permitiendo",
   "impermeabilizar",
   "resistencia",
   "corrosion",
   "abrasion",
   "intemperie",
   "sustancias",
   "agresivas",
   "acidos",
   "alcalis",
   "disolventes",
   "forma",
   "membrana",
   "monolitica",
   "costuras",
   "acepta",
   "modificaciones",
   "reparaciones",
   "siendo",
   "resistente",
   "ataque",
   "microorganismos",
   "variaciones",
   "temperatura",
   "respuesta",
   "requisitos",
   "norma",
   "impermeabilizacion",
   "principales",
   "ventajas",
   "cumple",
   "especificaciones",
   "garantizando",
   "total",
   "seguridad",
   "embalses"
  ],
  "ficha": true
 },
 {
  "slug": "cq-impermix",
  "name": "CQ Impermix",
  "sub": "",
  "desc": "CQ Impermix es un aditivo impermeabilizante para morteros y hormigones, que reacciona con el cemento durante el proceso de hidratación bloqueando el sistema capilar.",
  "family": "impermeabilizantes",
  "familyLabel": "Impermeabilizantes",
  "color": "#14B8A6",
  "initials": "IMPERMIX",
  "kw": [
   "humedad",
   "infiltracion",
   "filtracion",
   "goteras",
   "estanqueidad",
   "tanque",
   "cisterna",
   "subsuelo",
   "impermix",
   "impermeabilizacion",
   "mortero",
   "aditivo",
   "impermeabilizante",
   "morteros",
   "hormigones",
   "reacciona",
   "cemento",
   "proceso",
   "hidratacion",
   "bloqueando",
   "sistema",
   "capilar",
   "propiedades",
   "ventajas",
   "sencilla",
   "facil",
   "fraguado",
   "normal",
   "altera",
   "tiempo",
   "curado",
   "previene",
   "eflorescencia",
   "tiene",
   "efecto",
   "permanente",
   "impide",
   "vapor",
   "permitiendo",
   "hormigon",
   "respire",
   "campos",
   "recomienda",
   "altos",
   "impermeabilidad",
   "tales",
   "depositos",
   "tuberias",
   "recubrimientos",
   "externos",
   "internos",
   "pisos",
   "paredes",
   "contacto",
   "directo",
   "suelo",
   "colocacion",
   "ladrillos",
   "cimientos",
   "impermeable"
  ],
  "ficha": true
 },
 {
  "slug": "cq-seal-admix",
  "name": "CQ Seal Admix",
  "sub": "",
  "desc": "CQ Seal Admix es un aditivo en polvo para impermeabilización por cristalización integral, agregado a la mezcla de hormigón durante su producción. Reacciona con la humedad del hormigón fresco, interactuando con los productos de hidratación del cemento, formando",
  "family": "impermeabilizantes",
  "familyLabel": "Impermeabilizantes",
  "color": "#14B8A6",
  "initials": "SEAL ADMIX",
  "kw": [
   "humedad",
   "infiltracion",
   "filtracion",
   "goteras",
   "estanqueidad",
   "tanque",
   "cisterna",
   "subsuelo",
   "seal",
   "admix",
   "aditivo",
   "cristalizante",
   "impermeabilizacion",
   "autocristalizacion",
   "hormigon",
   "polvo",
   "cristalizacion",
   "integral",
   "anadido",
   "mezcla",
   "durante",
   "produccion",
   "reacciona",
   "fresco",
   "interactuando",
   "productos",
   "hidratacion",
   "cemento",
   "formando",
   "estructura",
   "cristalina",
   "insoluble",
   "llena",
   "poros",
   "capilares",
   "microestructura",
   "bloquean",
   "permanentemente",
   "contribuye",
   "durabilidad",
   "armado",
   "reduce",
   "permeabilidad",
   "inhibe",
   "penetracion",
   "sulfatos",
   "cloruros",
   "mantiene",
   "pasivacion",
   "armadura",
   "principales",
   "ventajas",
   "elimina",
   "resiste",
   "altas",
   "presiones",
   "hidrostaticas",
   "positivas",
   "negativas",
   "aumenta"
  ],
  "ficha": true
 },
 {
  "slug": "cq-seal-argamassas-polimericas",
  "name": "CQ Seal Argamassas Poliméricas",
  "sub": "",
  "desc": "La línea CQ SEAL está compuesta por morteros poliméricos bicomponentes (A+B) de altas prestaciones, desarrollados para satisfacer diferentes necesidades de impermeabilización. Todo a base de cementos especiales, aditivos minerales y polímeros de excelente cali",
  "family": "impermeabilizantes",
  "familyLabel": "Impermeabilizantes",
  "color": "#14B8A6",
  "initials": "SEAL ARGAMASSAS…",
  "kw": [
   "humedad",
   "infiltracion",
   "filtracion",
   "goteras",
   "estanqueidad",
   "tanque",
   "cisterna",
   "subsuelo",
   "seal",
   "argamassas",
   "polimericas",
   "impermeabilizantes",
   "linha",
   "sistema",
   "completo",
   "impermeabilizacion",
   "profesional",
   "necesidad",
   "morteros",
   "polimericos",
   "bicomponentes",
   "altas",
   "prestaciones",
   "certificado",
   "linea",
   "completa",
   "compuesta",
   "desarrollados",
   "satisfacer",
   "diferentes",
   "necesidades",
   "cementos",
   "especiales",
   "aditivos",
   "minerales",
   "polimeros",
   "excelente",
   "calidad",
   "formando",
   "recubrimientos",
   "adherencia",
   "impermeables",
   "bicomponente",
   "componente",
   "resina",
   "liquida",
   "cemento",
   "polvo",
   "facil",
   "mezcla",
   "certificaciones",
   "potable",
   "versatilidad",
   "brocha",
   "airless",
   "varios",
   "espesores",
   "multiples",
   "sustratos",
   "seguridad"
  ],
  "ficha": false
 },
 {
  "slug": "bio260-power",
  "name": "Bio260 Power",
  "sub": "Removedor de Hormigón",
  "desc": "Bio360 Power es un producto desarrollado para remover hormigón seco o incrustado de camiones o otras superficies. A pesar de ser un ácido sintético fuerte, su fórmula exclusiva no daña la piel ni otros materiales, como pintura y vidrio. Comprobado por varias a",
  "family": "limpieza",
  "familyLabel": "Limpieza y removedores",
  "color": "#10B981",
  "initials": "BIO260 POWER",
  "kw": [
   "limpiar",
   "concreto endurecido",
   "residuo",
   "mixer",
   "betonera",
   "hormigonera",
   "equipo sucio",
   "biodegradable",
   "bio260",
   "power",
   "removedor",
   "hormigon",
   "potencia",
   "desarrollado",
   "remover",
   "incrustado",
   "camiones",
   "otras",
   "superficies",
   "pesar",
   "acido",
   "sintetico",
   "fuerte",
   "formula",
   "exclusiva",
   "otros",
   "materiales",
   "pintura",
   "vidrio",
   "comprobado",
   "varias",
   "agencias",
   "internacionales",
   "cumple",
   "rigurosos",
   "estandares",
   "ambientales",
   "seguridad",
   "personal",
   "principales",
   "ventajas",
   "utilizado",
   "cualquier",
   "parte",
   "camion",
   "disuelve",
   "muriatico",
   "necesario",
   "utilizar",
   "genera",
   "costos",
   "adicionales",
   "salud",
   "peligros",
   "campos",
   "aplicar",
   "superficie",
   "desee",
   "eliminar",
   "mortero"
  ],
  "ficha": true
 },
 {
  "slug": "bio360-power",
  "name": "Bio360 Power",
  "sub": "",
  "desc": "Bio360 Power es un producto diseñado para eliminar hormigón seco o incrustado de camiones u otras superficies. A pesar de ser un ácido sintético fuerte, su fórmula exclusiva no daña la piel ni otros materiales, como pintura y vidrio. Comprobado por varias agen",
  "family": "limpieza",
  "familyLabel": "Limpieza y removedores",
  "color": "#10B981",
  "initials": "BIO360 POWER",
  "kw": [
   "limpiar",
   "concreto endurecido",
   "residuo",
   "mixer",
   "betonera",
   "hormigonera",
   "equipo sucio",
   "biodegradable",
   "bio360",
   "power",
   "energia",
   "removedor",
   "hormigon",
   "desarrollado",
   "eliminar",
   "incrustado",
   "camiones",
   "otras",
   "superficies",
   "pesar",
   "acido",
   "sintetico",
   "fuerte",
   "formula",
   "exclusiva",
   "otros",
   "materiales",
   "pintura",
   "vidrio",
   "verificado",
   "varias",
   "agencias",
   "estandares",
   "internacionales",
   "cumple",
   "rigurosos",
   "ambientales",
   "seguridad",
   "personal",
   "principales",
   "ventajas",
   "utilizar",
   "cualquier",
   "parte",
   "camion",
   "disuelve",
   "muriatico",
   "necesario",
   "genera",
   "costos",
   "extras",
   "salud",
   "riesgos",
   "peligrosos",
   "campos",
   "aplicar",
   "superficie",
   "productos",
   "mortero",
   "cemento"
  ],
  "ficha": true
 },
 {
  "slug": "cq-acryltop-plus",
  "name": "CQ Acryltop Plus",
  "sub": "",
  "desc": "CQ Acryltop Plus es un barniz concentrado a base de agua, que cuando se aplica a la superficie forma una Película incolora y brillante, que mejora la impermeabilidad y la protección contra la lluvia y los rayos. UV, aumentando la resistencia al desgaste y faci",
  "family": "limpieza",
  "familyLabel": "Limpieza y removedores",
  "color": "#10B981",
  "initials": "ACRYLTOP PLUS",
  "kw": [
   "limpiar",
   "concreto endurecido",
   "residuo",
   "mixer",
   "betonera",
   "hormigonera",
   "equipo sucio",
   "biodegradable",
   "acryltop",
   "plus",
   "resina",
   "acrilica",
   "barniz",
   "concentrado",
   "aplica",
   "superficie",
   "forma",
   "pelicula",
   "incolora",
   "brillante",
   "mejora",
   "impermeabilidad",
   "proteccion",
   "contra",
   "lluvia",
   "rayos",
   "aumentando",
   "resistencia",
   "desgaste",
   "facilitando",
   "limpieza",
   "superficies",
   "facil",
   "secado",
   "rapido",
   "principales",
   "ventajas",
   "inodoro",
   "aplicarse",
   "lugares",
   "ventilacion",
   "aspecto",
   "barrera",
   "humedad",
   "exterior",
   "aumenta",
   "durabilidad",
   "sustrato",
   "protege",
   "algas",
   "hongos",
   "previene",
   "eflorescencia",
   "campos",
   "recomienda",
   "fachadas",
   "hormigon",
   "visto",
   "baldosas",
   "mineral"
  ],
  "ficha": true
 },
 {
  "slug": "cq-lumina",
  "name": "CQ Lumina",
  "sub": "Agregado Fotoluminiscente",
  "desc": "CQ LUMINA se produce con una mezcla de pigmento fotoluminiscente y resina de poliéster formando un gránulo irregular. No es tóxico y tiene una excelente resistencia a la intemperie. Puede ser utilizado sobre superficies de hormigón, pavimento asfáltico, entre ",
  "family": "pigmentos",
  "familyLabel": "Pigmentos",
  "color": "#EC4899",
  "initials": "LUMINA",
  "kw": [
   "color",
   "colorear",
   "rojo",
   "negro",
   "amarillo",
   "ocre",
   "lumina",
   "agregado",
   "fotoluminiscente",
   "produce",
   "mezcla",
   "pigmento",
   "resina",
   "poliester",
   "formando",
   "granular",
   "irregular",
   "toxico",
   "tiene",
   "excelente",
   "resistencia",
   "intemperie",
   "utilizar",
   "superficies",
   "hormigon",
   "pavimento",
   "asfaltico",
   "otros",
   "funcion",
   "demarcar",
   "asegurar",
   "seguridad",
   "ambientes",
   "ademas",
   "usarse",
   "jugar",
   "papel",
   "estetico",
   "ornamental",
   "principales",
   "ventajas",
   "resistente",
   "ambiental",
   "renovable",
   "autogenerada",
   "disminucion",
   "electricidad",
   "garantiza",
   "entornos",
   "desempena",
   "campos",
   "recomienda",
   "expuesto",
   "carriles",
   "bordes",
   "piscinas",
   "pisos",
   "baldosas",
   "datos",
   "tecnicos"
  ],
  "ficha": true
 },
 {
  "slug": "cq-ferrox-color",
  "name": "Pigmentos - Color CQ Ferrox",
  "sub": "",
  "desc": "Los pigmentos Ferrox Color son pigmentos inorgánicos a base de óxido de hierro sintetizado, listos para el consumo. Desarrollados especialmente para hormigones y morteros, tienen excelente poder de pigmentación y excelente dispersión, proporcionando colores má",
  "family": "pigmentos",
  "familyLabel": "Pigmentos",
  "color": "#EC4899",
  "initials": "PIGMENTOS - COL…",
  "kw": [
   "color",
   "colorear",
   "rojo",
   "negro",
   "amarillo",
   "ocre",
   "pigmentos",
   "ferrox",
   "pigmento",
   "hormigon",
   "oxido",
   "colores",
   "vivos",
   "estables",
   "disponibles",
   "poder",
   "tenido",
   "resistencia",
   "rayos",
   "pigmentacion",
   "profesional",
   "hormigones",
   "morteros",
   "inorganicos",
   "hierro",
   "sintetizado",
   "listos",
   "consumo",
   "desarrollados",
   "especialmente",
   "tienen",
   "excelente",
   "dispersion",
   "proporcionando",
   "cobertura",
   "intensidad",
   "menos",
   "mismo",
   "ahorro",
   "estable",
   "degrada",
   "climaticas",
   "adversas",
   "mantiene",
   "original",
   "durante",
   "decolora",
   "resistente",
   "solar",
   "permanentes",
   "larga",
   "duracion",
   "compatibilidad",
   "total",
   "compatible",
   "alcalinidad",
   "cemento",
   "interfiere",
   "curado",
   "seguro"
  ],
  "ficha": false
 },
 {
  "slug": "pigmentos-ferrox-color",
  "name": "Pigmentos de color Ferrox",
  "sub": "",
  "desc": "Los pigmentos Ferrox Color son pigmentos inorgánicos, a base de óxido de hierro sintetizado, listos para consumo. Desarrollado especialmente para hormigones y morteros. Tiene un poder excelente pigmentación y excelente dispersión, proporcionando colores más vi",
  "family": "pigmentos",
  "familyLabel": "Pigmentos",
  "color": "#EC4899",
  "initials": "PIGMENTOS DE CO…",
  "kw": [
   "color",
   "colorear",
   "rojo",
   "negro",
   "amarillo",
   "ocre",
   "pigmentos",
   "ferrox",
   "emitida",
   "oxido",
   "hierro",
   "sintetizado",
   "inorganicos",
   "listos",
   "consumo",
   "desarrollado",
   "especialmente",
   "hormigones",
   "morteros",
   "tiene",
   "poder",
   "excelente",
   "pigmentacion",
   "dispersion",
   "proporcionando",
   "colores",
   "vivos",
   "estables",
   "principales",
   "ventajas",
   "colorante",
   "compatible",
   "alcalinidad",
   "cemento",
   "estable",
   "degrada",
   "climaticas",
   "adversas",
   "resistente",
   "rayos",
   "solares",
   "campos",
   "utilizan",
   "general",
   "disponible",
   "naranja",
   "marron",
   "datos",
   "tecnicos",
   "pigmento",
   "apariencia",
   "polvo",
   "absorcion",
   "aceite",
   "gramos",
   "solubilidad",
   "retencion",
   "malla",
   "embalaje",
   "almacenamiento"
  ],
  "ficha": true
 },
 {
  "slug": "cq-hardfloor-lithium-plus",
  "name": "CQ HARDFLOOR LITHIUM PLUS",
  "sub": "",
  "desc": "",
  "family": "pisos",
  "familyLabel": "Pisos industriales",
  "color": "#94A3B8",
  "initials": "HARDFLOOR LITHI…",
  "kw": [
   "piso industrial",
   "galpon",
   "pulido",
   "brillo",
   "polvo",
   "desgaste",
   "trafico",
   "hardfloor",
   "lithium",
   "plus",
   "litio",
   "endurecedor",
   "superficies",
   "hidrofugo",
   "hormigon",
   "silicato",
   "nanosilice",
   "conjunto",
   "tienen",
   "mayor",
   "poder",
   "penetracion",
   "matriz",
   "aplica",
   "pisos",
   "cemento",
   "provoca",
   "reaccion",
   "hidroxido",
   "calcio",
   "tratar",
   "catalizado",
   "hidratacion",
   "transformandolo",
   "cristales",
   "dureza",
   "estabilidad",
   "rellenar",
   "poros",
   "genera",
   "superficie",
   "resistencia",
   "abrasion",
   "libre",
   "creacion",
   "liberacion",
   "propiedades",
   "ventajas",
   "produce",
   "efecto",
   "antipolvo",
   "mejora",
   "disminucion",
   "permeabilidad",
   "brillar",
   "sustrato",
   "facil",
   "campos",
   "recomienda",
   "diferentes"
  ],
  "ficha": true
 },
 {
  "slug": "cq-siltop-aqua",
  "name": "CQ Siltop Aqua",
  "sub": "",
  "desc": "CQ Siltop Aqua es un repelente de agua incoloro de alta tecnología, a base de silano-siloxano oligomérico disuelto en agua. Crea una barrera invisible que vuelve las superficies minerales repelentes al agua y al aceite, evitando la penetración de la humedad si",
  "family": "pisos",
  "familyLabel": "Pisos industriales",
  "color": "#94A3B8",
  "initials": "SILTOP AQUA",
  "kw": [
   "piso industrial",
   "galpon",
   "pulido",
   "brillo",
   "polvo",
   "desgaste",
   "trafico",
   "siltop",
   "aqua",
   "repelente",
   "incoloro",
   "silano",
   "siloxano",
   "oligomerico",
   "disuelto",
   "superficies",
   "minerales",
   "repelentes",
   "aceite",
   "evitando",
   "penetracion",
   "humedad",
   "principales",
   "ventajas",
   "inodoro",
   "inflamable",
   "altera",
   "apariencia",
   "sustrato",
   "protege",
   "superficie",
   "contra",
   "accion",
   "lluvia",
   "rayos",
   "ultravioleta",
   "facilita",
   "respiracion",
   "secado",
   "permitiendo",
   "vapor",
   "barrera",
   "exterior",
   "aumenta",
   "durabilidad",
   "preserva",
   "belleza",
   "natural",
   "previene",
   "formacion",
   "hongos",
   "manchas",
   "eflorescencia",
   "buena",
   "resistencia",
   "acciones",
   "quimicas",
   "campos",
   "recomendado",
   "diferentes"
  ],
  "ficha": true
 },
 {
  "slug": "cq-siltop-stone",
  "name": "CQ Siltop Stone",
  "sub": "",
  "desc": "",
  "family": "pisos",
  "familyLabel": "Pisos industriales",
  "color": "#94A3B8",
  "initials": "SILTOP STONE",
  "kw": [
   "piso industrial",
   "galpon",
   "pulido",
   "brillo",
   "polvo",
   "desgaste",
   "trafico",
   "siltop",
   "stone",
   "repelente",
   "hidrofugante",
   "incoloro",
   "silano",
   "siloxano",
   "oligomerico",
   "medio",
   "disolvente",
   "desarrollado",
   "especialmente",
   "piedras",
   "superficies",
   "minerales",
   "haciendolas",
   "repelentes",
   "aceite",
   "propiedades",
   "ventajas",
   "altera",
   "apariencia",
   "sustrato",
   "protege",
   "superficie",
   "contra",
   "lluvia",
   "facilita",
   "respiracion",
   "secado",
   "permitiendo",
   "vapor",
   "barrera",
   "humedad",
   "exterior",
   "aumenta",
   "durabilidad",
   "preserva",
   "belleza",
   "natural",
   "previene",
   "formacion",
   "hongos",
   "manchas",
   "buena",
   "resistencia",
   "acciones",
   "quimicas",
   "campo",
   "recomienda",
   "naturales",
   "granitos",
   "marmoles"
  ],
  "ficha": true
 },
 {
  "slug": "cq-concreto-seco-press-mix",
  "name": "Aditivos para Hormigón Seco – CQ Concreto Seco Press Mix – Comparativo de Aditivos",
  "sub": "",
  "desc": "CQ Press Mix es un aditivo plastificante líquido y concentrado, listo para el consumo. Desarrollado para aplicaciones con hormigón seco, actúa sobre el agua de amasado para mejorar la compactación, aumentar la plasticidad de la masa y reducir las fisuras, cont",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "ADITIVOS PARA H…",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "aditivos",
   "seco",
   "concreto",
   "press",
   "mix",
   "plastificante",
   "densificante",
   "compresion",
   "mejor",
   "acabado",
   "menos",
   "perdidas",
   "produccion",
   "soluciones",
   "fluido",
   "prefabricados",
   "armado",
   "pretensado",
   "vibroprensado",
   "rendimiento",
   "acelerar",
   "ritmo",
   "aditivo",
   "liquido",
   "concentrado",
   "listo",
   "consumo",
   "desarrollado",
   "aplicaciones",
   "amasado",
   "mejorar",
   "compactacion",
   "aumentar",
   "plasticidad",
   "reducir",
   "fisuras",
   "contribuyendo",
   "menor",
   "desperdicio",
   "mayor",
   "eficiencia",
   "proceso",
   "productivo",
   "aumenta",
   "grado",
   "contribuye",
   "mecanica",
   "reduce",
   "absorcion",
   "mezcla"
  ],
  "ficha": false
 },
 {
  "slug": "q-flow-ultratech-90",
  "name": "Aditivos superplastificantes – Q Flow Ultratech 90",
  "sub": "",
  "desc": "CQ Flow Ultratech 90 es un aditivo superplastificante de tercera generación, a base de éter de policarboxilato, listo para el consumo, libre de cloruros y compatible con distintos tipos de cemento. Fue desarrollado para hormigones que requieren un aumento en l",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "ADITIVOS SUPERP…",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "aditivos",
   "superplastificantes",
   "flow",
   "ultratech",
   "superplastificante",
   "reduccion",
   "ganancia",
   "inicial",
   "productividad",
   "muros",
   "prefabricados",
   "tercera",
   "generacion",
   "desencofrado",
   "temprano",
   "aditivo",
   "policarboxilato",
   "listo",
   "consumo",
   "libre",
   "cloruros",
   "compatible",
   "distintos",
   "tipos",
   "cemento",
   "desarrollado",
   "hormigones",
   "requieren",
   "aumento",
   "especialmente",
   "rapido",
   "incrementa",
   "contribuye",
   "mayor",
   "compresion",
   "flexion",
   "promueve",
   "significativo",
   "fresco",
   "mejora",
   "capacidad",
   "armaduras",
   "facilita",
   "hormigonado",
   "control",
   "amasado",
   "alcanzar",
   "dependiendo",
   "dosis",
   "mezcla"
  ],
  "ficha": false
 },
 {
  "slug": "cq-air-flow-9040",
  "name": "CQ Air Flow 9040",
  "sub": "",
  "desc": "CQ Air Flow 9040 es un aditivo superplastificante de tercera generación, a base de éter de policarboxilato, listo para usar, libre de cloruros y compatible con distintos tipos de cemento. Fue desarrollado para hormigones que requieren una gran abertura de asen",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "AIR FLOW 9040",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "air",
   "flow",
   "9040",
   "aditivos",
   "superplastificantes",
   "superplastificante",
   "aumenta",
   "mantiene",
   "incorporado",
   "mejora",
   "apertura",
   "asentamiento",
   "control",
   "especifica",
   "tercera",
   "generacion",
   "grandes",
   "aberturas",
   "aditivo",
   "policarboxilato",
   "listo",
   "libre",
   "cloruros",
   "compatible",
   "distintos",
   "tipos",
   "cemento",
   "desarrollado",
   "hormigones",
   "requieren",
   "abertura",
   "desincorporacion",
   "brindando",
   "excelente",
   "fresco",
   "aumento",
   "significativo",
   "fundicion",
   "esparcimiento",
   "faciles",
   "reduccion",
   "mezclado",
   "mejor",
   "eficiencia",
   "contribuye",
   "mayor",
   "rendimiento",
   "cohesion",
   "mezcla",
   "signos"
  ],
  "ficha": false
 },
 {
  "slug": "cq-air-flow-9055",
  "name": "CQ Air Flow 9055",
  "sub": "",
  "desc": "CQ Air Flow 9055 está compuesto por aditivos superplastificantes de tercera generación basados en policarboxilato, listo para el consumo, completamente libre de cloruros y compatible con diferentes tipos de cemento. Fue desarrollado para hormigones que requier",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "AIR FLOW 9055",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "air",
   "flow",
   "9055",
   "flujo",
   "superplastificante",
   "compuesto",
   "aditivos",
   "superplastificantes",
   "tercera",
   "generacion",
   "basados",
   "policarboxilato",
   "listo",
   "consumo",
   "completamente",
   "libre",
   "cloruros",
   "compatible",
   "diferentes",
   "tipos",
   "cemento",
   "desarrollado",
   "hormigones",
   "requieren",
   "apertura",
   "desincorporacion",
   "proporcionando",
   "excelente",
   "cumple",
   "requisitos",
   "norma",
   "brasilena",
   "clasificado",
   "reductor",
   "incorporador",
   "principales",
   "ventajas",
   "aumento",
   "significativo",
   "fresco",
   "reduccion",
   "amasado",
   "mayor",
   "cohesion",
   "consiguiente",
   "manifestaciones",
   "segregacion",
   "cambia",
   "tiempo",
   "fraguado"
  ],
  "ficha": true
 },
 {
  "slug": "cq-calplast-a",
  "name": "CQ Calplast A",
  "sub": "",
  "desc": "CQ Calplast A es un aditivo líquido que proporciona una excelente trabajabilidad a morteros y hormigones. Su formulación contribuye al ahorro de material, rapidez en la ejecución y acabado superior, además de ayudar a mantener el aire incorporado en los morter",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "CALPLAST A",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "calplast",
   "plastificante",
   "incorporador",
   "morteros",
   "hormigones",
   "aditivo",
   "proporciona",
   "excelente",
   "liquido",
   "facilita",
   "trabajo",
   "ahorro",
   "material",
   "rapidez",
   "ejecucion",
   "acabado",
   "principales",
   "diferencias",
   "linea",
   "mantenimiento",
   "incorporado",
   "estabilizados",
   "mantener",
   "condicion",
   "plastica",
   "horas",
   "abrasador",
   "cilindrico",
   "uniforme",
   "favoreciendo",
   "absorbiendo",
   "expansion",
   "contraccion",
   "ciclos",
   "hielo",
   "descongelar",
   "cumple",
   "requisitos",
   "norma",
   "brasilena",
   "clasificado",
   "entrador",
   "ventajas",
   "mayor",
   "adherencia",
   "cohesion",
   "ausencia",
   "grietas",
   "menor",
   "exudacion"
  ],
  "ficha": true
 },
 {
  "slug": "cq-celmix",
  "name": "CQ Celmix",
  "sub": "Incorporador de aire para mortero y hormigón",
  "desc": "CQ Celmix es un aditivo espumante desarrollado para hormigón celular, morteros y hormigones ligeros. Permite producir materiales con densidad variable, según la aplicación, contribuyendo a una mayor homogeneidad, plasticidad y trabajabilidad de la mezcla.",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "CELMIX",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "celmix",
   "incorporador",
   "mortero",
   "aditivo",
   "espumante",
   "desarrollado",
   "celular",
   "morteros",
   "hormigones",
   "ligeros",
   "permite",
   "produccion",
   "densidad",
   "variable",
   "segun",
   "cumple",
   "requisitos",
   "norma",
   "brasilena",
   "clasificado",
   "ligero",
   "principales",
   "ventajas",
   "mayor",
   "homogeneidad",
   "plasticidad",
   "buena",
   "retencion",
   "produce",
   "espuma",
   "duradera",
   "obtener",
   "diferente",
   "campos",
   "aislamiento",
   "termico",
   "materiales",
   "acustico",
   "datos",
   "tecnicos",
   "funcion",
   "embalaje",
   "aspecto",
   "liquido",
   "vendido",
   "bombonas",
   "contenedor",
   "granel",
   "contiene",
   "productos"
  ],
  "ficha": true
 },
 {
  "slug": "cq-cola-35",
  "name": "CQ Cola 35",
  "sub": "",
  "desc": "CQ Cola 35 es un pegamento especial a base de PVA, en medio acuoso, de altas prestaciones que proporciona Excelente adherencia de morteros a los más diversos soportes. Proporciona mayor elasticidad y así Mayor resistencia al desgaste y a los golpes.",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "COLA 35",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "cola",
   "adhesivo",
   "mortero",
   "revestimiento",
   "pegamento",
   "especial",
   "medio",
   "acuoso",
   "altas",
   "prestaciones",
   "proporciona",
   "excelente",
   "adherencia",
   "morteros",
   "diversos",
   "soportes",
   "mayor",
   "elasticidad",
   "desgaste",
   "golpes",
   "principales",
   "ventajas",
   "facil",
   "mantiene",
   "caracteristicas",
   "incluso",
   "presencia",
   "humedad",
   "amplia",
   "sustratos",
   "plasticidad",
   "reduce",
   "permeabilidad",
   "minimiza",
   "contraccion",
   "cemento",
   "masas",
   "mixtas",
   "alcalinidad",
   "toxico",
   "inflamable",
   "rendimiento",
   "campos",
   "reparacion",
   "mamposteria",
   "pisos",
   "lechadas",
   "fijador",
   "instalacion",
   "azulejos"
  ],
  "ficha": true
 },
 {
  "slug": "cq-flow-1850",
  "name": "CQ Flow 1850",
  "sub": "Superplastificante tipo RA2",
  "desc": "CQ Flow 1850 está compuesto por aditivos superplastificantes de tercera generación a base de policarboxilato, Listo para el consumo, completamente libre de cloruros y compatible con distintos tipos de cemento. fue desarrollado para reducir grandes cantidades d",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "FLOW 1850",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "flow",
   "1850",
   "superplastificante",
   "flujo",
   "compuesto",
   "aditivos",
   "superplastificantes",
   "tercera",
   "generacion",
   "policarboxilato",
   "listo",
   "consumo",
   "completamente",
   "libre",
   "cloruros",
   "compatible",
   "distintos",
   "tipos",
   "cemento",
   "desarrollado",
   "reducir",
   "grandes",
   "cantidades",
   "mezcla",
   "dependiendo",
   "reduccion",
   "deseada",
   "proporcionando",
   "excelente",
   "alterar",
   "tiempo",
   "fraguado",
   "cumple",
   "requisitos",
   "norma",
   "brasilena",
   "clasificado",
   "reductor",
   "principales",
   "ventajas",
   "aumenta",
   "compresion",
   "flexion",
   "aumento",
   "significativo",
   "fresco",
   "capacidad",
   "armaduras",
   "amasado",
   "mayor"
  ],
  "ficha": true
 },
 {
  "slug": "cq-flow-377",
  "name": "CQ Flow 377",
  "sub": "Superplastificante tipo RA2-A",
  "desc": "CQ Flow 377 está compuesto por aditivos superplastificantes de tercera generación a base de policarboxilato, Listo para el consumo, completamente libre de cloruros y compatible con distintos tipos de cemento. Desarrollado especialmente para hormigones que requ",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "FLOW 377",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "flow",
   "377",
   "superplastificante",
   "flujo",
   "compuesto",
   "aditivos",
   "superplastificantes",
   "tercera",
   "generacion",
   "policarboxilato",
   "listo",
   "consumo",
   "completamente",
   "libre",
   "cloruros",
   "compatible",
   "distintos",
   "tipos",
   "cemento",
   "desarrollado",
   "especialmente",
   "hormigones",
   "requieren",
   "aumento",
   "inicial",
   "utilizado",
   "fabricacion",
   "muros",
   "prefabricados",
   "rapida",
   "liberacion",
   "formas",
   "cumple",
   "requisitos",
   "norma",
   "brasilena",
   "clasificada",
   "reductor",
   "acelerador",
   "principales",
   "ventajas",
   "aumenta",
   "compresion",
   "flexion",
   "significativo",
   "fresco",
   "capacidad",
   "armaduras",
   "reduccion",
   "amasado"
  ],
  "ficha": true
 },
 {
  "slug": "cq-flow-3865-sp",
  "name": "CQ Flow 3865 SP",
  "sub": "Superplastificante tipo RA2",
  "desc": "CQ Flow 3865 SP está compuesto por aditivos superplastificantes de tercera generación a base de policarboxilato, listo para el consumo, completamente libre de cloruros y compatible con diferentes tipos de cemento. Fue desarrollado para reducir una gran cantida",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "FLOW 3865 SP",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "flow",
   "3865",
   "superplastificante",
   "compuesto",
   "aditivos",
   "superplastificantes",
   "tercera",
   "generacion",
   "policarboxilato",
   "listo",
   "consumo",
   "completamente",
   "libre",
   "cloruros",
   "compatible",
   "diferentes",
   "tipos",
   "cemento",
   "desarrollado",
   "reducir",
   "cantidad",
   "amasado",
   "dependiendo",
   "reduccion",
   "deseada",
   "proporcionando",
   "excelente",
   "alterar",
   "tiempo",
   "fraguado",
   "respuesta",
   "requisitos",
   "norma",
   "brasilena",
   "clasificado",
   "reductor",
   "principales",
   "ventajas",
   "aumenta",
   "compresion",
   "flexion",
   "aumento",
   "significativo",
   "fresco",
   "capacidad",
   "armaduras",
   "mayor",
   "cohesion",
   "consiguiente",
   "manifestaciones"
  ],
  "ficha": true
 },
 {
  "slug": "cq-flow-8375",
  "name": "CQ Flow 8375",
  "sub": "",
  "desc": "CQ Flow 8375 está compuesto por aditivos superplastificantes de tercera generación a base de policarboxilato, Listo para el consumo, completamente libre de cloruros y compatible con distintos tipos de cemento. Ellos actúan reduciendo el agua de mezcla y aument",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "FLOW 8375",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "flow",
   "8375",
   "flujo",
   "superplastificante",
   "compuesto",
   "aditivos",
   "superplastificantes",
   "tercera",
   "generacion",
   "policarboxilato",
   "listo",
   "consumo",
   "completamente",
   "libre",
   "cloruros",
   "compatible",
   "distintos",
   "tipos",
   "cemento",
   "ellos",
   "actuan",
   "reduciendo",
   "mezcla",
   "aumentando",
   "mantenimiento",
   "cumple",
   "requisitos",
   "principales",
   "ventajas",
   "aumenta",
   "compresion",
   "inicial",
   "final",
   "ampliacion",
   "significativa",
   "mayor",
   "cohesion",
   "consiguiente",
   "reduccion",
   "manifestaciones",
   "segregacion",
   "cambia",
   "tiempo",
   "fraguado",
   "mejora",
   "impermeabilidad",
   "durabilidad",
   "campos",
   "recomienda",
   "diferentes"
  ],
  "ficha": true
 },
 {
  "slug": "cq-flow-8406",
  "name": "CQ Flow 8406",
  "sub": "",
  "desc": "CQ Flow 8406 está compuesto por aditivos superplastificantes de tercera generación a base de policarboxilato, Listo para el consumo, completamente libre de cloruros y compatible con distintos tipos de cemento. fue desarrollado para reducir grandes cantidades d",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "FLOW 8406",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "flow",
   "8406",
   "flujo",
   "superplastificante",
   "compuesto",
   "aditivos",
   "superplastificantes",
   "tercera",
   "generacion",
   "policarboxilato",
   "listo",
   "consumo",
   "completamente",
   "libre",
   "cloruros",
   "compatible",
   "distintos",
   "tipos",
   "cemento",
   "desarrollado",
   "reducir",
   "grandes",
   "cantidades",
   "mezcla",
   "dependiendo",
   "reduccion",
   "deseada",
   "proporcionando",
   "excelente",
   "alterar",
   "tiempo",
   "fraguado",
   "cumple",
   "requisitos",
   "norma",
   "brasilena",
   "clasificado",
   "reductor",
   "principales",
   "ventajas",
   "aumenta",
   "compresion",
   "flexion",
   "aumento",
   "significativo",
   "fresco",
   "capacidad",
   "armaduras",
   "amasado",
   "mayor"
  ],
  "ficha": true
 },
 {
  "slug": "cq-flow-8415",
  "name": "CQ Flow 8415",
  "sub": "",
  "desc": "CQ Flow 8415 está compuesto por aditivos superplastificantes de tercera generación basados en policarboxilato, listo para el consumo, completamente libre de cloruros y compatible con diversos tipos de cemento. Fue desarrollado para reducir grandes cantidades d",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "FLOW 8415",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "flow",
   "8415",
   "flujo",
   "superplastificante",
   "compuesto",
   "aditivos",
   "superplastificantes",
   "tercera",
   "generacion",
   "basados",
   "policarboxilato",
   "listo",
   "consumo",
   "completamente",
   "libre",
   "cloruros",
   "compatible",
   "diversos",
   "tipos",
   "cemento",
   "desarrollado",
   "reducir",
   "grandes",
   "cantidades",
   "amasado",
   "dependiendo",
   "reduccion",
   "deseada",
   "proporcionando",
   "excelente",
   "cambiar",
   "coger",
   "tiempo",
   "cumple",
   "requisitos",
   "norma",
   "brasilena",
   "clasificado",
   "reductor",
   "principales",
   "ventajas",
   "aumenta",
   "compresion",
   "flexion",
   "aumento",
   "significativo",
   "fresco",
   "capacidad",
   "atravesar",
   "refuerzo"
  ],
  "ficha": true
 },
 {
  "slug": "cq-flow-cenere-70",
  "name": "CQ Flow Cenere 70",
  "sub": "Superplastificante tipo RA2",
  "desc": "CQ Flow Cenere 70 es un aditivo superplastificante a base de éter policarboxilato, listo para el consumo, libre de cloruros y compatible con distintos tipos de cemento. Fue desarrollado para reducir el agua de amasado, manteniendo o aumentando la fluidez del h",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "FLOW CENERE 70",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "flow",
   "cenere",
   "superplastificante",
   "innovador",
   "aditivo",
   "disenado",
   "ofrecer",
   "solucion",
   "eficaz",
   "reducir",
   "mezclado",
   "manteniendo",
   "aumentando",
   "fresco",
   "ideal",
   "amplia",
   "aplicaciones",
   "concretas",
   "promoviendo",
   "mejoras",
   "efectos",
   "significativos",
   "mecanica",
   "durabilidad",
   "impermeabilidad",
   "estructuras",
   "principales",
   "ventajas",
   "mayor",
   "mejora",
   "significativamente",
   "compresion",
   "flexion",
   "contribuyendo",
   "robustas",
   "duraderas",
   "excepcional",
   "proporciona",
   "aumento",
   "significativo",
   "facilitando",
   "complejas",
   "traves",
   "refuerzos",
   "densos",
   "necesidad",
   "vibracion",
   "reduccion",
   "permite",
   "cantidad"
  ],
  "ficha": true
 },
 {
  "slug": "cq-flow-edge-70",
  "name": "CQ Flow Edge 70",
  "sub": "Superplastificante tipo RA2-A",
  "desc": "CQ Flow Edge 70 es un aditivo superplastificante de tercera generación, a base de éter policarboxilato, listo para el consumo, libre de cloruros y compatible con distintos tipos de cemento. Fue desarrollado para hormigones que requieren un aumento en la resist",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "FLOW EDGE 70",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "flow",
   "edge",
   "superplastificante",
   "compuesto",
   "aditivos",
   "superplastificantes",
   "tercera",
   "generacion",
   "policarboxilato",
   "listo",
   "consumo",
   "completamente",
   "libre",
   "cloruros",
   "compatible",
   "diferentes",
   "tipos",
   "cemento",
   "desarrollado",
   "especialmente",
   "hormigones",
   "requieren",
   "mayor",
   "iniciales",
   "utilizados",
   "fabricacion",
   "muros",
   "prefabricados",
   "desencofrado",
   "temprano",
   "cumple",
   "requisitos",
   "norma",
   "brasilena",
   "clasificado",
   "reductor",
   "acelerador",
   "principales",
   "ventajas",
   "aumenta",
   "compresion",
   "flexion",
   "inicial",
   "aumento",
   "significativo",
   "fresco",
   "capacidad",
   "armaduras",
   "reduccion",
   "amasado"
  ],
  "ficha": true
 },
 {
  "slug": "cq-flow-ultratech",
  "name": "CQ Flow Ultratech",
  "sub": "",
  "desc": "CQ Flow Ultratech está compuesto por aditivos superplastificantes de tercera generación basados en Policarboxilato de última generación, listo para su consumo, completamente libre de cloruros y Compatible con diferentes tipos de cemento. Fue desarrollado para ",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "FLOW ULTRATECH",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "flow",
   "ultratech",
   "superplastificante",
   "compuesto",
   "aditivos",
   "superplastificantes",
   "tercera",
   "generacion",
   "basados",
   "policarboxilato",
   "ultima",
   "listo",
   "consumo",
   "completamente",
   "libre",
   "cloruros",
   "compatible",
   "diferentes",
   "tipos",
   "cemento",
   "desarrollado",
   "ultra",
   "rendimiento",
   "reducir",
   "cantidad",
   "amasado",
   "proporcionando",
   "excelente",
   "cambiar",
   "tiempo",
   "fraguado",
   "principales",
   "ventajas",
   "aumenta",
   "compresion",
   "flexion",
   "aumento",
   "significativo",
   "fresco",
   "capacidad",
   "atravesar",
   "refuerzo",
   "reduccion",
   "mayor",
   "cohesion",
   "consiguiente",
   "manifestaciones",
   "segregacion",
   "cambia",
   "prolonga"
  ],
  "ficha": true
 },
 {
  "slug": "cq-flow-ultratech-70",
  "name": "CQ Flow Ultratech 70",
  "sub": "Superplastificante tipo RA2-A",
  "desc": "CQ Flow Ultratech 70 está compuesto por aditivos superplastificantes de tercera generación a base de policarboxilato, listo para el consumo, completamente libre de cloruros y compatible con diferentes tipos de cemento. Desarrollado especialmente para hormigone",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "FLOW ULTRATECH …",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "flow",
   "ultratech",
   "superplastificante",
   "compuesto",
   "aditivos",
   "superplastificantes",
   "tercera",
   "generacion",
   "policarboxilato",
   "listo",
   "consumo",
   "completamente",
   "libre",
   "cloruros",
   "compatible",
   "diferentes",
   "tipos",
   "cemento",
   "desarrollado",
   "especialmente",
   "hormigones",
   "requieren",
   "mayor",
   "iniciales",
   "utilizados",
   "fabricacion",
   "muros",
   "prefabricados",
   "desencofrado",
   "temprano",
   "cumple",
   "requisitos",
   "norma",
   "brasilena",
   "clasificado",
   "reductor",
   "acelerador",
   "principales",
   "ventajas",
   "aumenta",
   "compresion",
   "flexion",
   "inicial",
   "aumento",
   "significativo",
   "fresco",
   "capacidad",
   "armaduras",
   "reduccion",
   "amasado"
  ],
  "ficha": true
 },
 {
  "slug": "cq-flow-wall-9000",
  "name": "CQ Flow Wall 9000",
  "sub": "Superplastificante tipo RA2",
  "desc": "CQ Flow Wall 9000 es un aditivo superplastificante de tercera generación, a base de éter de policarboxilato, listo para el consumo, libre de cloruros y compatible con distintos tipos de cemento. Fue desarrollado especialmente para el hormigón utilizado en la f",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "FLOW WALL 9000",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "flow",
   "wall",
   "9000",
   "superplastificante",
   "compuesto",
   "aditivos",
   "superplastificantes",
   "tercera",
   "generacion",
   "basados",
   "policarboxilato",
   "listo",
   "consumo",
   "completamente",
   "libre",
   "cloruros",
   "compatible",
   "diferentes",
   "tipos",
   "cemento",
   "desarrollado",
   "especialmente",
   "utilizado",
   "fabricacion",
   "muros",
   "porque",
   "ademas",
   "reducir",
   "cantidad",
   "amasado",
   "proporciona",
   "aumento",
   "desencofrado",
   "inicial",
   "rapido",
   "mejorar",
   "acabado",
   "paredes",
   "cumple",
   "requisitos",
   "norma",
   "brasilena",
   "clasificado",
   "reductor",
   "principales",
   "ventajas",
   "aumenta",
   "compresion",
   "flexion",
   "significativo"
  ],
  "ficha": true
 },
 {
  "slug": "cq-plast-mr-825",
  "name": "CQ Plast MR 825",
  "sub": "",
  "desc": "CQ Plast MR 825 está compuesto por aditivos superplastificantes de tercera generación a base de policarboxilato, listo para el consumo, completamente libre de cloruros y compatible con diferentes tipos de cemento. Actúan para reducir el agua de mezcla y aument",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "PLAST MR 825",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "plast",
   "825",
   "superplastificante",
   "compuesto",
   "aditivos",
   "superplastificantes",
   "tercera",
   "generacion",
   "policarboxilato",
   "listo",
   "consumo",
   "completamente",
   "libre",
   "cloruros",
   "compatible",
   "diferentes",
   "tipos",
   "cemento",
   "actuan",
   "reducir",
   "mezcla",
   "aumentar",
   "mantenimiento",
   "tiene",
   "enfocados",
   "pisos",
   "obras",
   "especiales",
   "requieren",
   "reduccion",
   "amasando",
   "dosis",
   "habitual",
   "varia",
   "cumple",
   "requisitos",
   "norma",
   "brasilena",
   "clasificado",
   "reductor",
   "principales",
   "ventajas",
   "aumenta",
   "compresion",
   "inicial",
   "final",
   "ampliacion",
   "significativa",
   "mayor",
   "cohesion"
  ],
  "ficha": true
 },
 {
  "slug": "cq-plast-mr-855",
  "name": "CQ Plast MR 855",
  "sub": "",
  "desc": "CQ Plast MR 855 está compuesto por aditivos superplastificantes modificados, listos para el consumo, Completamente libre de cloruros y compatible con diferentes tipos de cemento. Trabajan para reducir mezclar agua y aumentar el mantenimiento de la trabajabilid",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "PLAST MR 855",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "plast",
   "855",
   "superplastificante",
   "compuesto",
   "aditivos",
   "superplastificantes",
   "modificados",
   "listos",
   "consumo",
   "completamente",
   "libre",
   "cloruros",
   "compatible",
   "diferentes",
   "tipos",
   "cemento",
   "trabajan",
   "reducir",
   "mezclar",
   "aumentar",
   "mantenimiento",
   "centra",
   "pisos",
   "obras",
   "especiales",
   "requieran",
   "reduccion",
   "amasado",
   "dosis",
   "habitual",
   "varia",
   "cumple",
   "requisitos",
   "estandar",
   "brasil",
   "clasificado",
   "reductor",
   "retardador",
   "principales",
   "ventajas",
   "aumenta",
   "compresion",
   "inicial",
   "final",
   "aumento",
   "importante",
   "mayor",
   "cohesion",
   "consiguiente",
   "manifestaciones"
  ],
  "ficha": true
 },
 {
  "slug": "cq-plast-pa-220",
  "name": "CQ Plast PA 220",
  "sub": "",
  "desc": "CQ Plast PA 220 es un aditivo plastificante polifuncional a base de lignosulfonatos y materias primas naturales, listo para usar, libre de cloruros y compatible con todas las clases de cemento Portland. Fue desarrollado para hormigón elaborado en planta, hormi",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "PLAST PA 220",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "plast",
   "220",
   "plastificante",
   "fraguado",
   "acelerado",
   "aditivo",
   "lignosulfonatos",
   "materias",
   "primas",
   "naturales",
   "libre",
   "cloruros",
   "listo",
   "desarrollado",
   "elaborado",
   "planta",
   "bombeado",
   "obras",
   "general",
   "pisos",
   "cimentaciones",
   "puentes",
   "presas",
   "tuneles",
   "reducir",
   "amasado",
   "dependiendo",
   "dosificacion",
   "traza",
   "caracteristicas",
   "materiales",
   "utilizados",
   "compatible",
   "todas",
   "clases",
   "cemento",
   "portland",
   "dosis",
   "habitual",
   "varia",
   "cumple",
   "requisitos",
   "estandar",
   "brasilena",
   "clasificada",
   "reductor",
   "acelerador",
   "principales",
   "ventajas",
   "mayor"
  ],
  "ficha": true
 },
 {
  "slug": "cq-plast-pm-5000",
  "name": "CQ Plast PM 5000",
  "sub": "Plastificante Densificante",
  "desc": "CQ Plast PM 5000 es un aditivo plastificante líquido y concentrado, listo para el consumo. En dilución con agua de amasado mejora la compactación y reduce el agrietamiento, lo que resulta en una menor tasa de residuos y aumento de la plasticidad. Utilizado en ",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "PLAST PM 5000",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "plast",
   "5000",
   "plastificante",
   "densificante",
   "aditivo",
   "liquido",
   "concentrado",
   "listo",
   "consumo",
   "dilucion",
   "amasado",
   "mejora",
   "compactacion",
   "reduce",
   "agrietamiento",
   "resulta",
   "menor",
   "residuos",
   "aumento",
   "plasticidad",
   "utilizado",
   "fabricacion",
   "productos",
   "respuesta",
   "requisitos",
   "norma",
   "brasilena",
   "clasificado",
   "vibropresado",
   "principales",
   "ventajas",
   "aumenta",
   "reduciendo",
   "absorcion",
   "mezcla",
   "notablemente",
   "acabado",
   "pieza",
   "grado",
   "aumentando",
   "impermeabilidad",
   "deslizamiento",
   "desmoldar",
   "cohesion",
   "rotura",
   "durante",
   "lubricidad",
   "desgaste",
   "moldes",
   "hilos"
  ],
  "ficha": true
 },
 {
  "slug": "cq-plast-pn-7016",
  "name": "CQ Plast PN 7016",
  "sub": "",
  "desc": "CQ Plast PN 7016 es un aditivo plastificante polifuncional a base de lignosulfonatos y materias primas naturales, listo para usar, libre de cloruros y compatible con todas las clases de cemento Portland. Fue desarrollado para hormigón elaborado en planta, horm",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "PLAST PN 7016",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "plast",
   "7016",
   "plastificante",
   "fraguado",
   "normal",
   "aditivo",
   "lignosulfonatos",
   "materias",
   "primas",
   "naturales",
   "libre",
   "cloruros",
   "listo",
   "desarrollado",
   "elaborado",
   "planta",
   "bombeado",
   "obras",
   "general",
   "pisos",
   "cimentaciones",
   "puentes",
   "presas",
   "tuneles",
   "reducir",
   "amasado",
   "dependiendo",
   "dosificacion",
   "traza",
   "caracteristicas",
   "materiales",
   "utilizados",
   "compatible",
   "todas",
   "clases",
   "cemento",
   "portland",
   "dosis",
   "habitual",
   "varia",
   "cumple",
   "requisitos",
   "estandar",
   "brasil",
   "clasificado",
   "reductor",
   "retardador",
   "principales",
   "ventajas",
   "mayor"
  ],
  "ficha": true
 },
 {
  "slug": "cq-plast-sp-2000",
  "name": "CQ Plast SP 2000",
  "sub": "Superplastificante",
  "desc": "CQ Plast SP 2000 es un aditivo superplastificante a base de naftalenos y materias primas naturales secundarias, listo para usar, libre de cloruros y compatible con todas las clases de cemento Portland. Fue desarrollado para aplicaciones en prefabricados, pisos",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "PLAST SP 2000",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "plast",
   "2000",
   "superplastificante",
   "aditivo",
   "naftalenos",
   "materias",
   "primas",
   "naturales",
   "secundarias",
   "libre",
   "cloruros",
   "listo",
   "disenado",
   "pisos",
   "prefabricados",
   "industriales",
   "sitios",
   "construccion",
   "especiales",
   "puentes",
   "tuneles",
   "dosis",
   "habitual",
   "varia",
   "reducir",
   "mezclando",
   "dependiendo",
   "dosificacion",
   "caracteristicas",
   "materiales",
   "utilizados",
   "compatible",
   "todos",
   "grados",
   "cemento",
   "portland",
   "cumple",
   "requisitos",
   "norma",
   "brasilena",
   "clasificado",
   "reductor",
   "principales",
   "ventajas",
   "aumento",
   "inicial",
   "final",
   "respecto",
   "linea",
   "anterior"
  ],
  "ficha": true
 },
 {
  "slug": "cq-press-mix-super",
  "name": "CQ Press Mix Super",
  "sub": "Plastificante Densificante",
  "desc": "CQ Press Mix Super es un aditivo plastificante líquido y concentrado, listo para el consumo. En dilución con agua de amasado mejora la compactación y reduce el agrietamiento, lo que resulta en una menor tasa de residuos y aumento de la plasticidad. Utilizado e",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "PRESS MIX SUPER",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "press",
   "mix",
   "super",
   "plastificante",
   "densificante",
   "aditivo",
   "liquido",
   "concentrado",
   "listo",
   "consumo",
   "dilucion",
   "amasado",
   "mejora",
   "compactacion",
   "reduce",
   "agrietamiento",
   "resulta",
   "menor",
   "residuos",
   "aumento",
   "plasticidad",
   "utilizado",
   "fabricacion",
   "productos",
   "respuesta",
   "requisitos",
   "norma",
   "brasilena",
   "clasificado",
   "vibropresado",
   "principales",
   "ventajas",
   "aumenta",
   "reduciendo",
   "absorcion",
   "mezcla",
   "notablemente",
   "acabado",
   "pieza",
   "grado",
   "aumentando",
   "impermeabilidad",
   "cohesion",
   "rotura",
   "durante",
   "lubricidad",
   "desgaste",
   "moldes",
   "hilos",
   "cemento"
  ],
  "ficha": true
 },
 {
  "slug": "cq-superplast-1000",
  "name": "CQ Superplast 1000",
  "sub": "Densificador Superplastificante",
  "desc": "CQ Superplast 1000 es un aditivo líquido, libre de cloruros y listo para el consumo. Desarrollado para hormigón seco, actúa sobre el agua de amasado para mejorar la compactación, aumentar la plasticidad de la masa y reducir las fisuras, contribuyendo a una men",
  "family": "plastificantes",
  "familyLabel": "Plastificantes",
  "color": "#3B82F6",
  "initials": "SUPERPLAST 1000",
  "kw": [
   "trabajabilidad",
   "bombeo",
   "fluidez",
   "reduccion de agua",
   "resistencia",
   "hormigon",
   "bloques",
   "paver",
   "adoquin",
   "premoldado",
   "superplast",
   "1000",
   "densificador",
   "superplastificante",
   "aditivo",
   "liquido",
   "libre",
   "cloruros",
   "listo",
   "consumo",
   "diluye",
   "amasado",
   "mejora",
   "compactacion",
   "reduce",
   "agrietamiento",
   "resulta",
   "menor",
   "desechos",
   "aumento",
   "plasticidad",
   "utilizados",
   "fabricacion",
   "productos",
   "canales",
   "pisos",
   "entrelazados",
   "bordillo",
   "tubos",
   "prensados",
   "alveolar",
   "cumple",
   "requisitos",
   "vibroprensado",
   "principales",
   "ventajas",
   "aumenta",
   "reduciendo",
   "absorcion",
   "mezcla",
   "notablemente",
   "acabado",
   "pieza",
   "grado",
   "aumentando",
   "impermeabilidad",
   "deslizamiento",
   "desmoldar",
   "cohesion",
   "rotura"
  ],
  "ficha": true
 },
 {
  "slug": "cq-construcao",
  "name": "PU - CQ Construção",
  "sub": "",
  "desc": "PU CQ Construção es un sellador y adhesivo impermeable, monocomponente y de elasticidad permanente. Tiene una excelente resistencia a la intemperie y a la luz solar, con excelente resistencia al envejecimiento. Producto a base de polímeros híbridos sintéticos,",
  "family": "selladores",
  "familyLabel": "Selladores y PU",
  "color": "#F26D21",
  "initials": "PU - CQ CONSTRU…",
  "kw": [
   "junta",
   "sellado",
   "dilatacion",
   "grieta estructural",
   "construcao",
   "resistencia",
   "rayos",
   "intemperie",
   "sellador",
   "poliuretano",
   "elastico",
   "sella",
   "protege",
   "cualquier",
   "superficie",
   "elasticidad",
   "permanente",
   "adhesion",
   "adhesivo",
   "impermeable",
   "monocomponente",
   "tiene",
   "excelente",
   "solar",
   "envejecimiento",
   "polimeros",
   "hibridos",
   "sinteticos",
   "quimicamente",
   "neutro",
   "corrosivo",
   "acepta",
   "pinturas",
   "movimiento",
   "constante",
   "juntas",
   "elongacion",
   "mantiene",
   "propiedades",
   "tiempo",
   "soporta",
   "temperaturas",
   "formulacion",
   "avanzada",
   "libre",
   "isocianatos",
   "disolventes",
   "acidos",
   "durante",
   "versatilidad",
   "multiples",
   "sustratos",
   "interno",
   "externo",
   "recomienda",
   "campos",
   "sellos",
   "industriales",
   "carrocerias",
   "baules"
  ],
  "ficha": false
 },
 {
  "slug": "pu-cq-40-cinza",
  "name": "PU CQ 40 - Cinza",
  "sub": "",
  "desc": "PU CQ 40 es un sellador y adhesivo impermeable, monocomponente y de elasticidad permanente. Tiene una excelente resistencia a la intemperie y a la luz solar, con excelente resistencia a envejecimiento. Es un producto no corrosivo, de poco olor y se puede pinta",
  "family": "selladores",
  "familyLabel": "Selladores y PU",
  "color": "#F26D21",
  "initials": "PU CQ 40 - CINZA",
  "kw": [
   "junta",
   "sellado",
   "dilatacion",
   "grieta estructural",
   "cinza",
   "sellador",
   "elastico",
   "poliuretano",
   "adhesivo",
   "impermeable",
   "monocomponente",
   "elasticidad",
   "permanente",
   "tiene",
   "excelente",
   "resistencia",
   "intemperie",
   "solar",
   "envejecimiento",
   "corrosivo",
   "pintar",
   "cumple",
   "normas",
   "campos",
   "recomienda",
   "hormigon",
   "madera",
   "vidrio",
   "metales",
   "piedras",
   "materiales",
   "ceramicos",
   "sellos",
   "carrocerias",
   "baules",
   "contenedores",
   "marcos",
   "armazones",
   "reparacion",
   "instalacion",
   "canalones",
   "tapajuntas",
   "relleno",
   "juntas",
   "verticales",
   "horizontales",
   "pegado",
   "ambientes",
   "humedos",
   "uniones",
   "diversas",
   "requieren",
   "datos",
   "tecnicos",
   "funcion",
   "embalaje",
   "comercializado",
   "aspecto",
   "viscosa",
   "densidad"
  ],
  "ficha": true
 },
 {
  "slug": "pu-cq-40-cinza-branco",
  "name": "PU CQ 40 - Cinza, branco",
  "sub": "",
  "desc": "PU CQ 40 es un sellador y adhesivo elástico, monocomponente, impermeable. permanente. Tiene una excelente resistencia a la intemperie y a la luz solar, con excelente resistencia al envejecimiento. Es un producto no corrosivo, de poco olor y se puede pintar. re",
  "family": "selladores",
  "familyLabel": "Selladores y PU",
  "color": "#F26D21",
  "initials": "PU CQ 40 - CINZ…",
  "kw": [
   "junta",
   "sellado",
   "dilatacion",
   "grieta estructural",
   "cinza",
   "branco",
   "sellador",
   "poliuretano",
   "elastico",
   "adhesivo",
   "monocomponente",
   "impermeable",
   "permanente",
   "tiene",
   "excelente",
   "resistencia",
   "intemperie",
   "solar",
   "envejecimiento",
   "corrosivo",
   "pintar",
   "respuesta",
   "normas",
   "campos",
   "recomienda",
   "propiedades",
   "adhesivas",
   "hormigon",
   "madera",
   "vidrio",
   "metales",
   "piedras",
   "materiales",
   "ceramicos",
   "sellos",
   "carrocerias",
   "baules",
   "contenedores",
   "marcos",
   "armazones",
   "reparacion",
   "instalacion",
   "canalones",
   "tapajuntas",
   "relleno",
   "juntas",
   "verticales",
   "horizontales",
   "pegado",
   "ambientes",
   "humedos",
   "uniones",
   "diversas",
   "requieren",
   "elasticidad",
   "datos",
   "tecnicos",
   "funcion",
   "embalaje",
   "comercial"
  ],
  "ficha": true
 },
 {
  "slug": "pu-cq-construcao",
  "name": "PU CQ Construção",
  "sub": "",
  "desc": "",
  "family": "selladores",
  "familyLabel": "Selladores y PU",
  "color": "#F26D21",
  "initials": "PU CQ CONSTRUÇÃO",
  "kw": [
   "junta",
   "sellado",
   "dilatacion",
   "grieta estructural",
   "construcao",
   "construccion",
   "sellador",
   "poliuretano",
   "elastico",
   "adhesivo",
   "monocomponente",
   "impermeable",
   "elasticidad",
   "permanente",
   "tiene",
   "excelente",
   "resistencia",
   "intemperie",
   "solar",
   "poseyendo",
   "envejecimiento",
   "polimeros",
   "hibridos",
   "sintetico",
   "quimicamente",
   "neutro",
   "corrosivo",
   "acepta",
   "pinturas",
   "libre",
   "isocianatos",
   "disolventes",
   "halogenos",
   "acidos",
   "campos",
   "recomienda",
   "propiedades",
   "adhesivas",
   "hormigon",
   "madera",
   "vidrio",
   "metales",
   "piedras",
   "materiales",
   "ceramicos",
   "sellos",
   "carrocerias",
   "baules",
   "contenedores",
   "marcos",
   "armazones",
   "reparacion",
   "instalacion",
   "canalones",
   "tapajuntas",
   "relleno",
   "juntas",
   "verticales",
   "horizontales",
   "uniones"
  ],
  "ficha": true
 },
 {
  "slug": "pu-cq-construcao-870-g",
  "name": "PU CQ Construção - 870 g",
  "sub": "Sellador Elástico de Poliuretano",
  "desc": "PU CQ Construção es un sellador y adhesivo elástico, monocomponente, impermeable. permanente. Tiene una excelente resistencia a la intemperie y a la luz solar, con excelente resistencia al envejecimiento. Es un producto a base de polímeros híbridos sintéticos,",
  "family": "selladores",
  "familyLabel": "Selladores y PU",
  "color": "#F26D21",
  "initials": "PU CQ CONSTRUÇÃ…",
  "kw": [
   "junta",
   "sellado",
   "dilatacion",
   "grieta estructural",
   "construcao",
   "870",
   "sellador",
   "elastico",
   "poliuretano",
   "construccion",
   "adhesivo",
   "monocomponente",
   "impermeable",
   "permanente",
   "tiene",
   "excelente",
   "resistencia",
   "intemperie",
   "solar",
   "envejecimiento",
   "polimeros",
   "hibridos",
   "sinteticos",
   "quimicamente",
   "neutro",
   "corrosivo",
   "acepta",
   "pinturas",
   "libre",
   "isocianatos",
   "disolventes",
   "halogenos",
   "acidos",
   "campos",
   "recomienda",
   "hormigon",
   "madera",
   "vidrio",
   "metales",
   "piedras",
   "materiales",
   "ceramicos",
   "sellos",
   "carrocerias",
   "baules",
   "contenedores",
   "marcos",
   "armazones",
   "reparacion",
   "instalacion",
   "canalones",
   "tapajuntas",
   "relleno",
   "juntas",
   "verticales",
   "horizontales",
   "uniones",
   "diversas",
   "requieren",
   "elasticidad"
  ],
  "ficha": true
 }
]
